#define EOT_DESC_STORE_ALL_ID_DEFINE \
EOT_CONST_CONSTANT_CONSTANT_DESC_ID,\
EOT_CONST_CONSTANT_DESC_EX_ID,\
EOT_CONST_FISH_ROOM_DESC_ID,\
EOT_CONST_FISH_GUNVALUE_DESC_ID,\
EOT_CONST_FISH_CTRLLEVEL_DESC_ID,\
EOT_CONST_FISH_DESC_EX_ID,\

