#define EOT_DESC_STORE_ALL_REGISTER_DEFINE \
REGISTER_DESCSTORE(ConstantConstantDesc);\
REGISTER_DESCSTORE_EX(ConstantDescEx);\
REGISTER_DESCSTORE(FishRoomDesc);\
REGISTER_DESCSTORE(FishGunvalueDesc);\
REGISTER_DESCSTORE(FishCtrllevelDesc);\
REGISTER_DESCSTORE_EX(FishDescEx);\

