// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: E_Escort.proto

#ifndef PROTOBUF_E_5fEscort_2eproto__INCLUDED
#define PROTOBUF_E_5fEscort_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "yd_fieldoptions.pb.h"
// @@protoc_insertion_point(includes)

namespace proto_ff {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_E_5fEscort_2eproto();
void protobuf_AssignDesc_E_5fEscort_2eproto();
void protobuf_ShutdownFile_E_5fEscort_2eproto();

class E_EscortEscort;
class Sheet_EscortEscort;
class E_EscortChanceEscortDesc;
class E_EscortChance;
class Sheet_EscortChance;
class E_EscortRewardRewardDesc;
class E_EscortReward;
class Sheet_EscortReward;
class E_EscortConst;
class Sheet_EscortConst;

// ===================================================================

class E_EscortEscort : public ::google::protobuf::Message {
 public:
  E_EscortEscort();
  virtual ~E_EscortEscort();

  E_EscortEscort(const E_EscortEscort& from);

  inline E_EscortEscort& operator=(const E_EscortEscort& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const E_EscortEscort& default_instance();

  void Swap(E_EscortEscort* other);

  // implements Message ----------------------------------------------

  E_EscortEscort* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const E_EscortEscort& from);
  void MergeFrom(const E_EscortEscort& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 m_convoyId = 1;
  inline bool has_m_convoyid() const;
  inline void clear_m_convoyid();
  static const int kMConvoyIdFieldNumber = 1;
  inline ::google::protobuf::int32 m_convoyid() const;
  inline void set_m_convoyid(::google::protobuf::int32 value);

  // optional string m_convoyName = 2;
  inline bool has_m_convoyname() const;
  inline void clear_m_convoyname();
  static const int kMConvoyNameFieldNumber = 2;
  inline const ::std::string& m_convoyname() const;
  inline void set_m_convoyname(const ::std::string& value);
  inline void set_m_convoyname(const char* value);
  inline void set_m_convoyname(const char* value, size_t size);
  inline ::std::string* mutable_m_convoyname();
  inline ::std::string* release_m_convoyname();
  inline void set_allocated_m_convoyname(::std::string* m_convoyname);

  // optional int32 m_MonsterId = 3;
  inline bool has_m_monsterid() const;
  inline void clear_m_monsterid();
  static const int kMMonsterIdFieldNumber = 3;
  inline ::google::protobuf::int32 m_monsterid() const;
  inline void set_m_monsterid(::google::protobuf::int32 value);

  // optional string m_scalle = 4;
  inline bool has_m_scalle() const;
  inline void clear_m_scalle();
  static const int kMScalleFieldNumber = 4;
  inline const ::std::string& m_scalle() const;
  inline void set_m_scalle(const ::std::string& value);
  inline void set_m_scalle(const char* value);
  inline void set_m_scalle(const char* value, size_t size);
  inline ::std::string* mutable_m_scalle();
  inline ::std::string* release_m_scalle();
  inline void set_allocated_m_scalle(::std::string* m_scalle);

  // optional int32 m_convoyLevel = 5;
  inline bool has_m_convoylevel() const;
  inline void clear_m_convoylevel();
  static const int kMConvoyLevelFieldNumber = 5;
  inline ::google::protobuf::int32 m_convoylevel() const;
  inline void set_m_convoylevel(::google::protobuf::int32 value);

  // optional int32 m_chance = 6;
  inline bool has_m_chance() const;
  inline void clear_m_chance();
  static const int kMChanceFieldNumber = 6;
  inline ::google::protobuf::int32 m_chance() const;
  inline void set_m_chance(::google::protobuf::int32 value);

  // optional int32 m_rewardLvMultiply = 7;
  inline bool has_m_rewardlvmultiply() const;
  inline void clear_m_rewardlvmultiply();
  static const int kMRewardLvMultiplyFieldNumber = 7;
  inline ::google::protobuf::int32 m_rewardlvmultiply() const;
  inline void set_m_rewardlvmultiply(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:proto_ff.E_EscortEscort)
 private:
  inline void set_has_m_convoyid();
  inline void clear_has_m_convoyid();
  inline void set_has_m_convoyname();
  inline void clear_has_m_convoyname();
  inline void set_has_m_monsterid();
  inline void clear_has_m_monsterid();
  inline void set_has_m_scalle();
  inline void clear_has_m_scalle();
  inline void set_has_m_convoylevel();
  inline void clear_has_m_convoylevel();
  inline void set_has_m_chance();
  inline void clear_has_m_chance();
  inline void set_has_m_rewardlvmultiply();
  inline void clear_has_m_rewardlvmultiply();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* m_convoyname_;
  ::google::protobuf::int32 m_convoyid_;
  ::google::protobuf::int32 m_monsterid_;
  ::std::string* m_scalle_;
  ::google::protobuf::int32 m_convoylevel_;
  ::google::protobuf::int32 m_chance_;
  ::google::protobuf::int32 m_rewardlvmultiply_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(7 + 31) / 32];

  friend void  protobuf_AddDesc_E_5fEscort_2eproto();
  friend void protobuf_AssignDesc_E_5fEscort_2eproto();
  friend void protobuf_ShutdownFile_E_5fEscort_2eproto();

  void InitAsDefaultInstance();
  static E_EscortEscort* default_instance_;
};
// -------------------------------------------------------------------

class Sheet_EscortEscort : public ::google::protobuf::Message {
 public:
  Sheet_EscortEscort();
  virtual ~Sheet_EscortEscort();

  Sheet_EscortEscort(const Sheet_EscortEscort& from);

  inline Sheet_EscortEscort& operator=(const Sheet_EscortEscort& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Sheet_EscortEscort& default_instance();

  void Swap(Sheet_EscortEscort* other);

  // implements Message ----------------------------------------------

  Sheet_EscortEscort* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Sheet_EscortEscort& from);
  void MergeFrom(const Sheet_EscortEscort& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .proto_ff.E_EscortEscort E_EscortEscort_List = 1;
  inline int e_escortescort_list_size() const;
  inline void clear_e_escortescort_list();
  static const int kEEscortEscortListFieldNumber = 1;
  inline const ::proto_ff::E_EscortEscort& e_escortescort_list(int index) const;
  inline ::proto_ff::E_EscortEscort* mutable_e_escortescort_list(int index);
  inline ::proto_ff::E_EscortEscort* add_e_escortescort_list();
  inline const ::google::protobuf::RepeatedPtrField< ::proto_ff::E_EscortEscort >&
      e_escortescort_list() const;
  inline ::google::protobuf::RepeatedPtrField< ::proto_ff::E_EscortEscort >*
      mutable_e_escortescort_list();

  // @@protoc_insertion_point(class_scope:proto_ff.Sheet_EscortEscort)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::proto_ff::E_EscortEscort > e_escortescort_list_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_E_5fEscort_2eproto();
  friend void protobuf_AssignDesc_E_5fEscort_2eproto();
  friend void protobuf_ShutdownFile_E_5fEscort_2eproto();

  void InitAsDefaultInstance();
  static Sheet_EscortEscort* default_instance_;
};
// -------------------------------------------------------------------

class E_EscortChanceEscortDesc : public ::google::protobuf::Message {
 public:
  E_EscortChanceEscortDesc();
  virtual ~E_EscortChanceEscortDesc();

  E_EscortChanceEscortDesc(const E_EscortChanceEscortDesc& from);

  inline E_EscortChanceEscortDesc& operator=(const E_EscortChanceEscortDesc& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const E_EscortChanceEscortDesc& default_instance();

  void Swap(E_EscortChanceEscortDesc* other);

  // implements Message ----------------------------------------------

  E_EscortChanceEscortDesc* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const E_EscortChanceEscortDesc& from);
  void MergeFrom(const E_EscortChanceEscortDesc& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 m_chance = 1;
  inline bool has_m_chance() const;
  inline void clear_m_chance();
  static const int kMChanceFieldNumber = 1;
  inline ::google::protobuf::int32 m_chance() const;
  inline void set_m_chance(::google::protobuf::int32 value);

  // optional int32 m_ID = 2;
  inline bool has_m_id() const;
  inline void clear_m_id();
  static const int kMIDFieldNumber = 2;
  inline ::google::protobuf::int32 m_id() const;
  inline void set_m_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:proto_ff.E_EscortChanceEscortDesc)
 private:
  inline void set_has_m_chance();
  inline void clear_has_m_chance();
  inline void set_has_m_id();
  inline void clear_has_m_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 m_chance_;
  ::google::protobuf::int32 m_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_E_5fEscort_2eproto();
  friend void protobuf_AssignDesc_E_5fEscort_2eproto();
  friend void protobuf_ShutdownFile_E_5fEscort_2eproto();

  void InitAsDefaultInstance();
  static E_EscortChanceEscortDesc* default_instance_;
};
// -------------------------------------------------------------------

class E_EscortChance : public ::google::protobuf::Message {
 public:
  E_EscortChance();
  virtual ~E_EscortChance();

  E_EscortChance(const E_EscortChance& from);

  inline E_EscortChance& operator=(const E_EscortChance& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const E_EscortChance& default_instance();

  void Swap(E_EscortChance* other);

  // implements Message ----------------------------------------------

  E_EscortChance* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const E_EscortChance& from);
  void MergeFrom(const E_EscortChance& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 m_convoyId = 1;
  inline bool has_m_convoyid() const;
  inline void clear_m_convoyid();
  static const int kMConvoyIdFieldNumber = 1;
  inline ::google::protobuf::int32 m_convoyid() const;
  inline void set_m_convoyid(::google::protobuf::int32 value);

  // repeated .proto_ff.E_EscortChanceEscortDesc m_escort = 2;
  inline int m_escort_size() const;
  inline void clear_m_escort();
  static const int kMEscortFieldNumber = 2;
  inline const ::proto_ff::E_EscortChanceEscortDesc& m_escort(int index) const;
  inline ::proto_ff::E_EscortChanceEscortDesc* mutable_m_escort(int index);
  inline ::proto_ff::E_EscortChanceEscortDesc* add_m_escort();
  inline const ::google::protobuf::RepeatedPtrField< ::proto_ff::E_EscortChanceEscortDesc >&
      m_escort() const;
  inline ::google::protobuf::RepeatedPtrField< ::proto_ff::E_EscortChanceEscortDesc >*
      mutable_m_escort();

  // @@protoc_insertion_point(class_scope:proto_ff.E_EscortChance)
 private:
  inline void set_has_m_convoyid();
  inline void clear_has_m_convoyid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::proto_ff::E_EscortChanceEscortDesc > m_escort_;
  ::google::protobuf::int32 m_convoyid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_E_5fEscort_2eproto();
  friend void protobuf_AssignDesc_E_5fEscort_2eproto();
  friend void protobuf_ShutdownFile_E_5fEscort_2eproto();

  void InitAsDefaultInstance();
  static E_EscortChance* default_instance_;
};
// -------------------------------------------------------------------

class Sheet_EscortChance : public ::google::protobuf::Message {
 public:
  Sheet_EscortChance();
  virtual ~Sheet_EscortChance();

  Sheet_EscortChance(const Sheet_EscortChance& from);

  inline Sheet_EscortChance& operator=(const Sheet_EscortChance& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Sheet_EscortChance& default_instance();

  void Swap(Sheet_EscortChance* other);

  // implements Message ----------------------------------------------

  Sheet_EscortChance* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Sheet_EscortChance& from);
  void MergeFrom(const Sheet_EscortChance& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .proto_ff.E_EscortChance E_EscortChance_List = 1;
  inline int e_escortchance_list_size() const;
  inline void clear_e_escortchance_list();
  static const int kEEscortChanceListFieldNumber = 1;
  inline const ::proto_ff::E_EscortChance& e_escortchance_list(int index) const;
  inline ::proto_ff::E_EscortChance* mutable_e_escortchance_list(int index);
  inline ::proto_ff::E_EscortChance* add_e_escortchance_list();
  inline const ::google::protobuf::RepeatedPtrField< ::proto_ff::E_EscortChance >&
      e_escortchance_list() const;
  inline ::google::protobuf::RepeatedPtrField< ::proto_ff::E_EscortChance >*
      mutable_e_escortchance_list();

  // @@protoc_insertion_point(class_scope:proto_ff.Sheet_EscortChance)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::proto_ff::E_EscortChance > e_escortchance_list_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_E_5fEscort_2eproto();
  friend void protobuf_AssignDesc_E_5fEscort_2eproto();
  friend void protobuf_ShutdownFile_E_5fEscort_2eproto();

  void InitAsDefaultInstance();
  static Sheet_EscortChance* default_instance_;
};
// -------------------------------------------------------------------

class E_EscortRewardRewardDesc : public ::google::protobuf::Message {
 public:
  E_EscortRewardRewardDesc();
  virtual ~E_EscortRewardRewardDesc();

  E_EscortRewardRewardDesc(const E_EscortRewardRewardDesc& from);

  inline E_EscortRewardRewardDesc& operator=(const E_EscortRewardRewardDesc& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const E_EscortRewardRewardDesc& default_instance();

  void Swap(E_EscortRewardRewardDesc* other);

  // implements Message ----------------------------------------------

  E_EscortRewardRewardDesc* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const E_EscortRewardRewardDesc& from);
  void MergeFrom(const E_EscortRewardRewardDesc& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 m_num = 1;
  inline bool has_m_num() const;
  inline void clear_m_num();
  static const int kMNumFieldNumber = 1;
  inline ::google::protobuf::int32 m_num() const;
  inline void set_m_num(::google::protobuf::int32 value);

  // optional int32 m_item = 2;
  inline bool has_m_item() const;
  inline void clear_m_item();
  static const int kMItemFieldNumber = 2;
  inline ::google::protobuf::int32 m_item() const;
  inline void set_m_item(::google::protobuf::int32 value);

  // optional int32 m_ID = 3;
  inline bool has_m_id() const;
  inline void clear_m_id();
  static const int kMIDFieldNumber = 3;
  inline ::google::protobuf::int32 m_id() const;
  inline void set_m_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:proto_ff.E_EscortRewardRewardDesc)
 private:
  inline void set_has_m_num();
  inline void clear_has_m_num();
  inline void set_has_m_item();
  inline void clear_has_m_item();
  inline void set_has_m_id();
  inline void clear_has_m_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 m_num_;
  ::google::protobuf::int32 m_item_;
  ::google::protobuf::int32 m_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_E_5fEscort_2eproto();
  friend void protobuf_AssignDesc_E_5fEscort_2eproto();
  friend void protobuf_ShutdownFile_E_5fEscort_2eproto();

  void InitAsDefaultInstance();
  static E_EscortRewardRewardDesc* default_instance_;
};
// -------------------------------------------------------------------

class E_EscortReward : public ::google::protobuf::Message {
 public:
  E_EscortReward();
  virtual ~E_EscortReward();

  E_EscortReward(const E_EscortReward& from);

  inline E_EscortReward& operator=(const E_EscortReward& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const E_EscortReward& default_instance();

  void Swap(E_EscortReward* other);

  // implements Message ----------------------------------------------

  E_EscortReward* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const E_EscortReward& from);
  void MergeFrom(const E_EscortReward& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 m_lv = 1;
  inline bool has_m_lv() const;
  inline void clear_m_lv();
  static const int kMLvFieldNumber = 1;
  inline ::google::protobuf::int32 m_lv() const;
  inline void set_m_lv(::google::protobuf::int32 value);

  // optional int64 m_exp = 2;
  inline bool has_m_exp() const;
  inline void clear_m_exp();
  static const int kMExpFieldNumber = 2;
  inline ::google::protobuf::int64 m_exp() const;
  inline void set_m_exp(::google::protobuf::int64 value);

  // repeated .proto_ff.E_EscortRewardRewardDesc m_reward = 3;
  inline int m_reward_size() const;
  inline void clear_m_reward();
  static const int kMRewardFieldNumber = 3;
  inline const ::proto_ff::E_EscortRewardRewardDesc& m_reward(int index) const;
  inline ::proto_ff::E_EscortRewardRewardDesc* mutable_m_reward(int index);
  inline ::proto_ff::E_EscortRewardRewardDesc* add_m_reward();
  inline const ::google::protobuf::RepeatedPtrField< ::proto_ff::E_EscortRewardRewardDesc >&
      m_reward() const;
  inline ::google::protobuf::RepeatedPtrField< ::proto_ff::E_EscortRewardRewardDesc >*
      mutable_m_reward();

  // @@protoc_insertion_point(class_scope:proto_ff.E_EscortReward)
 private:
  inline void set_has_m_lv();
  inline void clear_has_m_lv();
  inline void set_has_m_exp();
  inline void clear_has_m_exp();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int64 m_exp_;
  ::google::protobuf::RepeatedPtrField< ::proto_ff::E_EscortRewardRewardDesc > m_reward_;
  ::google::protobuf::int32 m_lv_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_E_5fEscort_2eproto();
  friend void protobuf_AssignDesc_E_5fEscort_2eproto();
  friend void protobuf_ShutdownFile_E_5fEscort_2eproto();

  void InitAsDefaultInstance();
  static E_EscortReward* default_instance_;
};
// -------------------------------------------------------------------

class Sheet_EscortReward : public ::google::protobuf::Message {
 public:
  Sheet_EscortReward();
  virtual ~Sheet_EscortReward();

  Sheet_EscortReward(const Sheet_EscortReward& from);

  inline Sheet_EscortReward& operator=(const Sheet_EscortReward& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Sheet_EscortReward& default_instance();

  void Swap(Sheet_EscortReward* other);

  // implements Message ----------------------------------------------

  Sheet_EscortReward* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Sheet_EscortReward& from);
  void MergeFrom(const Sheet_EscortReward& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .proto_ff.E_EscortReward E_EscortReward_List = 1;
  inline int e_escortreward_list_size() const;
  inline void clear_e_escortreward_list();
  static const int kEEscortRewardListFieldNumber = 1;
  inline const ::proto_ff::E_EscortReward& e_escortreward_list(int index) const;
  inline ::proto_ff::E_EscortReward* mutable_e_escortreward_list(int index);
  inline ::proto_ff::E_EscortReward* add_e_escortreward_list();
  inline const ::google::protobuf::RepeatedPtrField< ::proto_ff::E_EscortReward >&
      e_escortreward_list() const;
  inline ::google::protobuf::RepeatedPtrField< ::proto_ff::E_EscortReward >*
      mutable_e_escortreward_list();

  // @@protoc_insertion_point(class_scope:proto_ff.Sheet_EscortReward)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::proto_ff::E_EscortReward > e_escortreward_list_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_E_5fEscort_2eproto();
  friend void protobuf_AssignDesc_E_5fEscort_2eproto();
  friend void protobuf_ShutdownFile_E_5fEscort_2eproto();

  void InitAsDefaultInstance();
  static Sheet_EscortReward* default_instance_;
};
// -------------------------------------------------------------------

class E_EscortConst : public ::google::protobuf::Message {
 public:
  E_EscortConst();
  virtual ~E_EscortConst();

  E_EscortConst(const E_EscortConst& from);

  inline E_EscortConst& operator=(const E_EscortConst& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const E_EscortConst& default_instance();

  void Swap(E_EscortConst* other);

  // implements Message ----------------------------------------------

  E_EscortConst* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const E_EscortConst& from);
  void MergeFrom(const E_EscortConst& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 m_id = 1;
  inline bool has_m_id() const;
  inline void clear_m_id();
  static const int kMIdFieldNumber = 1;
  inline ::google::protobuf::int32 m_id() const;
  inline void set_m_id(::google::protobuf::int32 value);

  // optional int32 m_tokenId = 2;
  inline bool has_m_tokenid() const;
  inline void clear_m_tokenid();
  static const int kMTokenIdFieldNumber = 2;
  inline ::google::protobuf::int32 m_tokenid() const;
  inline void set_m_tokenid(::google::protobuf::int32 value);

  // optional int32 m_tokenNumber = 3;
  inline bool has_m_tokennumber() const;
  inline void clear_m_tokennumber();
  static const int kMTokenNumberFieldNumber = 3;
  inline ::google::protobuf::int32 m_tokennumber() const;
  inline void set_m_tokennumber(::google::protobuf::int32 value);

  // optional int32 m_dayTime = 4;
  inline bool has_m_daytime() const;
  inline void clear_m_daytime();
  static const int kMDayTimeFieldNumber = 4;
  inline ::google::protobuf::int32 m_daytime() const;
  inline void set_m_daytime(::google::protobuf::int32 value);

  // optional int32 m_freeNum = 5;
  inline bool has_m_freenum() const;
  inline void clear_m_freenum();
  static const int kMFreeNumFieldNumber = 5;
  inline ::google::protobuf::int32 m_freenum() const;
  inline void set_m_freenum(::google::protobuf::int32 value);

  // optional int32 m_mapId = 6;
  inline bool has_m_mapid() const;
  inline void clear_m_mapid();
  static const int kMMapIdFieldNumber = 6;
  inline ::google::protobuf::int32 m_mapid() const;
  inline void set_m_mapid(::google::protobuf::int32 value);

  // optional int32 m_startNpcID = 7;
  inline bool has_m_startnpcid() const;
  inline void clear_m_startnpcid();
  static const int kMStartNpcIDFieldNumber = 7;
  inline ::google::protobuf::int32 m_startnpcid() const;
  inline void set_m_startnpcid(::google::protobuf::int32 value);

  // optional int32 m_startNpcPointID = 8;
  inline bool has_m_startnpcpointid() const;
  inline void clear_m_startnpcpointid();
  static const int kMStartNpcPointIDFieldNumber = 8;
  inline ::google::protobuf::int32 m_startnpcpointid() const;
  inline void set_m_startnpcpointid(::google::protobuf::int32 value);

  // optional int32 m_overNpcID = 9;
  inline bool has_m_overnpcid() const;
  inline void clear_m_overnpcid();
  static const int kMOverNpcIDFieldNumber = 9;
  inline ::google::protobuf::int32 m_overnpcid() const;
  inline void set_m_overnpcid(::google::protobuf::int32 value);

  // optional int32 m_activityID = 10;
  inline bool has_m_activityid() const;
  inline void clear_m_activityid();
  static const int kMActivityIDFieldNumber = 10;
  inline ::google::protobuf::int32 m_activityid() const;
  inline void set_m_activityid(::google::protobuf::int32 value);

  // optional int32 m_taskID = 11;
  inline bool has_m_taskid() const;
  inline void clear_m_taskid();
  static const int kMTaskIDFieldNumber = 11;
  inline ::google::protobuf::int32 m_taskid() const;
  inline void set_m_taskid(::google::protobuf::int32 value);

  // optional int32 m_DistanceA = 12;
  inline bool has_m_distancea() const;
  inline void clear_m_distancea();
  static const int kMDistanceAFieldNumber = 12;
  inline ::google::protobuf::int32 m_distancea() const;
  inline void set_m_distancea(::google::protobuf::int32 value);

  // optional int32 m_DistanceB = 13;
  inline bool has_m_distanceb() const;
  inline void clear_m_distanceb();
  static const int kMDistanceBFieldNumber = 13;
  inline ::google::protobuf::int32 m_distanceb() const;
  inline void set_m_distanceb(::google::protobuf::int32 value);

  // optional int32 m_DistanceC = 14;
  inline bool has_m_distancec() const;
  inline void clear_m_distancec();
  static const int kMDistanceCFieldNumber = 14;
  inline ::google::protobuf::int32 m_distancec() const;
  inline void set_m_distancec(::google::protobuf::int32 value);

  // optional int32 m_timeLimit = 15;
  inline bool has_m_timelimit() const;
  inline void clear_m_timelimit();
  static const int kMTimeLimitFieldNumber = 15;
  inline ::google::protobuf::int32 m_timelimit() const;
  inline void set_m_timelimit(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:proto_ff.E_EscortConst)
 private:
  inline void set_has_m_id();
  inline void clear_has_m_id();
  inline void set_has_m_tokenid();
  inline void clear_has_m_tokenid();
  inline void set_has_m_tokennumber();
  inline void clear_has_m_tokennumber();
  inline void set_has_m_daytime();
  inline void clear_has_m_daytime();
  inline void set_has_m_freenum();
  inline void clear_has_m_freenum();
  inline void set_has_m_mapid();
  inline void clear_has_m_mapid();
  inline void set_has_m_startnpcid();
  inline void clear_has_m_startnpcid();
  inline void set_has_m_startnpcpointid();
  inline void clear_has_m_startnpcpointid();
  inline void set_has_m_overnpcid();
  inline void clear_has_m_overnpcid();
  inline void set_has_m_activityid();
  inline void clear_has_m_activityid();
  inline void set_has_m_taskid();
  inline void clear_has_m_taskid();
  inline void set_has_m_distancea();
  inline void clear_has_m_distancea();
  inline void set_has_m_distanceb();
  inline void clear_has_m_distanceb();
  inline void set_has_m_distancec();
  inline void clear_has_m_distancec();
  inline void set_has_m_timelimit();
  inline void clear_has_m_timelimit();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 m_id_;
  ::google::protobuf::int32 m_tokenid_;
  ::google::protobuf::int32 m_tokennumber_;
  ::google::protobuf::int32 m_daytime_;
  ::google::protobuf::int32 m_freenum_;
  ::google::protobuf::int32 m_mapid_;
  ::google::protobuf::int32 m_startnpcid_;
  ::google::protobuf::int32 m_startnpcpointid_;
  ::google::protobuf::int32 m_overnpcid_;
  ::google::protobuf::int32 m_activityid_;
  ::google::protobuf::int32 m_taskid_;
  ::google::protobuf::int32 m_distancea_;
  ::google::protobuf::int32 m_distanceb_;
  ::google::protobuf::int32 m_distancec_;
  ::google::protobuf::int32 m_timelimit_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(15 + 31) / 32];

  friend void  protobuf_AddDesc_E_5fEscort_2eproto();
  friend void protobuf_AssignDesc_E_5fEscort_2eproto();
  friend void protobuf_ShutdownFile_E_5fEscort_2eproto();

  void InitAsDefaultInstance();
  static E_EscortConst* default_instance_;
};
// -------------------------------------------------------------------

class Sheet_EscortConst : public ::google::protobuf::Message {
 public:
  Sheet_EscortConst();
  virtual ~Sheet_EscortConst();

  Sheet_EscortConst(const Sheet_EscortConst& from);

  inline Sheet_EscortConst& operator=(const Sheet_EscortConst& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Sheet_EscortConst& default_instance();

  void Swap(Sheet_EscortConst* other);

  // implements Message ----------------------------------------------

  Sheet_EscortConst* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Sheet_EscortConst& from);
  void MergeFrom(const Sheet_EscortConst& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .proto_ff.E_EscortConst E_EscortConst_List = 1;
  inline int e_escortconst_list_size() const;
  inline void clear_e_escortconst_list();
  static const int kEEscortConstListFieldNumber = 1;
  inline const ::proto_ff::E_EscortConst& e_escortconst_list(int index) const;
  inline ::proto_ff::E_EscortConst* mutable_e_escortconst_list(int index);
  inline ::proto_ff::E_EscortConst* add_e_escortconst_list();
  inline const ::google::protobuf::RepeatedPtrField< ::proto_ff::E_EscortConst >&
      e_escortconst_list() const;
  inline ::google::protobuf::RepeatedPtrField< ::proto_ff::E_EscortConst >*
      mutable_e_escortconst_list();

  // @@protoc_insertion_point(class_scope:proto_ff.Sheet_EscortConst)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::proto_ff::E_EscortConst > e_escortconst_list_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_E_5fEscort_2eproto();
  friend void protobuf_AssignDesc_E_5fEscort_2eproto();
  friend void protobuf_ShutdownFile_E_5fEscort_2eproto();

  void InitAsDefaultInstance();
  static Sheet_EscortConst* default_instance_;
};
// ===================================================================


// ===================================================================

// E_EscortEscort

// optional int32 m_convoyId = 1;
inline bool E_EscortEscort::has_m_convoyid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void E_EscortEscort::set_has_m_convoyid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void E_EscortEscort::clear_has_m_convoyid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void E_EscortEscort::clear_m_convoyid() {
  m_convoyid_ = 0;
  clear_has_m_convoyid();
}
inline ::google::protobuf::int32 E_EscortEscort::m_convoyid() const {
  return m_convoyid_;
}
inline void E_EscortEscort::set_m_convoyid(::google::protobuf::int32 value) {
  set_has_m_convoyid();
  m_convoyid_ = value;
}

// optional string m_convoyName = 2;
inline bool E_EscortEscort::has_m_convoyname() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void E_EscortEscort::set_has_m_convoyname() {
  _has_bits_[0] |= 0x00000002u;
}
inline void E_EscortEscort::clear_has_m_convoyname() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void E_EscortEscort::clear_m_convoyname() {
  if (m_convoyname_ != &::google::protobuf::internal::kEmptyString) {
    m_convoyname_->clear();
  }
  clear_has_m_convoyname();
}
inline const ::std::string& E_EscortEscort::m_convoyname() const {
  return *m_convoyname_;
}
inline void E_EscortEscort::set_m_convoyname(const ::std::string& value) {
  set_has_m_convoyname();
  if (m_convoyname_ == &::google::protobuf::internal::kEmptyString) {
    m_convoyname_ = new ::std::string;
  }
  m_convoyname_->assign(value);
}
inline void E_EscortEscort::set_m_convoyname(const char* value) {
  set_has_m_convoyname();
  if (m_convoyname_ == &::google::protobuf::internal::kEmptyString) {
    m_convoyname_ = new ::std::string;
  }
  m_convoyname_->assign(value);
}
inline void E_EscortEscort::set_m_convoyname(const char* value, size_t size) {
  set_has_m_convoyname();
  if (m_convoyname_ == &::google::protobuf::internal::kEmptyString) {
    m_convoyname_ = new ::std::string;
  }
  m_convoyname_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* E_EscortEscort::mutable_m_convoyname() {
  set_has_m_convoyname();
  if (m_convoyname_ == &::google::protobuf::internal::kEmptyString) {
    m_convoyname_ = new ::std::string;
  }
  return m_convoyname_;
}
inline ::std::string* E_EscortEscort::release_m_convoyname() {
  clear_has_m_convoyname();
  if (m_convoyname_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = m_convoyname_;
    m_convoyname_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void E_EscortEscort::set_allocated_m_convoyname(::std::string* m_convoyname) {
  if (m_convoyname_ != &::google::protobuf::internal::kEmptyString) {
    delete m_convoyname_;
  }
  if (m_convoyname) {
    set_has_m_convoyname();
    m_convoyname_ = m_convoyname;
  } else {
    clear_has_m_convoyname();
    m_convoyname_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional int32 m_MonsterId = 3;
inline bool E_EscortEscort::has_m_monsterid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void E_EscortEscort::set_has_m_monsterid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void E_EscortEscort::clear_has_m_monsterid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void E_EscortEscort::clear_m_monsterid() {
  m_monsterid_ = 0;
  clear_has_m_monsterid();
}
inline ::google::protobuf::int32 E_EscortEscort::m_monsterid() const {
  return m_monsterid_;
}
inline void E_EscortEscort::set_m_monsterid(::google::protobuf::int32 value) {
  set_has_m_monsterid();
  m_monsterid_ = value;
}

// optional string m_scalle = 4;
inline bool E_EscortEscort::has_m_scalle() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void E_EscortEscort::set_has_m_scalle() {
  _has_bits_[0] |= 0x00000008u;
}
inline void E_EscortEscort::clear_has_m_scalle() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void E_EscortEscort::clear_m_scalle() {
  if (m_scalle_ != &::google::protobuf::internal::kEmptyString) {
    m_scalle_->clear();
  }
  clear_has_m_scalle();
}
inline const ::std::string& E_EscortEscort::m_scalle() const {
  return *m_scalle_;
}
inline void E_EscortEscort::set_m_scalle(const ::std::string& value) {
  set_has_m_scalle();
  if (m_scalle_ == &::google::protobuf::internal::kEmptyString) {
    m_scalle_ = new ::std::string;
  }
  m_scalle_->assign(value);
}
inline void E_EscortEscort::set_m_scalle(const char* value) {
  set_has_m_scalle();
  if (m_scalle_ == &::google::protobuf::internal::kEmptyString) {
    m_scalle_ = new ::std::string;
  }
  m_scalle_->assign(value);
}
inline void E_EscortEscort::set_m_scalle(const char* value, size_t size) {
  set_has_m_scalle();
  if (m_scalle_ == &::google::protobuf::internal::kEmptyString) {
    m_scalle_ = new ::std::string;
  }
  m_scalle_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* E_EscortEscort::mutable_m_scalle() {
  set_has_m_scalle();
  if (m_scalle_ == &::google::protobuf::internal::kEmptyString) {
    m_scalle_ = new ::std::string;
  }
  return m_scalle_;
}
inline ::std::string* E_EscortEscort::release_m_scalle() {
  clear_has_m_scalle();
  if (m_scalle_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = m_scalle_;
    m_scalle_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void E_EscortEscort::set_allocated_m_scalle(::std::string* m_scalle) {
  if (m_scalle_ != &::google::protobuf::internal::kEmptyString) {
    delete m_scalle_;
  }
  if (m_scalle) {
    set_has_m_scalle();
    m_scalle_ = m_scalle;
  } else {
    clear_has_m_scalle();
    m_scalle_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional int32 m_convoyLevel = 5;
inline bool E_EscortEscort::has_m_convoylevel() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void E_EscortEscort::set_has_m_convoylevel() {
  _has_bits_[0] |= 0x00000010u;
}
inline void E_EscortEscort::clear_has_m_convoylevel() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void E_EscortEscort::clear_m_convoylevel() {
  m_convoylevel_ = 0;
  clear_has_m_convoylevel();
}
inline ::google::protobuf::int32 E_EscortEscort::m_convoylevel() const {
  return m_convoylevel_;
}
inline void E_EscortEscort::set_m_convoylevel(::google::protobuf::int32 value) {
  set_has_m_convoylevel();
  m_convoylevel_ = value;
}

// optional int32 m_chance = 6;
inline bool E_EscortEscort::has_m_chance() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void E_EscortEscort::set_has_m_chance() {
  _has_bits_[0] |= 0x00000020u;
}
inline void E_EscortEscort::clear_has_m_chance() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void E_EscortEscort::clear_m_chance() {
  m_chance_ = 0;
  clear_has_m_chance();
}
inline ::google::protobuf::int32 E_EscortEscort::m_chance() const {
  return m_chance_;
}
inline void E_EscortEscort::set_m_chance(::google::protobuf::int32 value) {
  set_has_m_chance();
  m_chance_ = value;
}

// optional int32 m_rewardLvMultiply = 7;
inline bool E_EscortEscort::has_m_rewardlvmultiply() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void E_EscortEscort::set_has_m_rewardlvmultiply() {
  _has_bits_[0] |= 0x00000040u;
}
inline void E_EscortEscort::clear_has_m_rewardlvmultiply() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void E_EscortEscort::clear_m_rewardlvmultiply() {
  m_rewardlvmultiply_ = 0;
  clear_has_m_rewardlvmultiply();
}
inline ::google::protobuf::int32 E_EscortEscort::m_rewardlvmultiply() const {
  return m_rewardlvmultiply_;
}
inline void E_EscortEscort::set_m_rewardlvmultiply(::google::protobuf::int32 value) {
  set_has_m_rewardlvmultiply();
  m_rewardlvmultiply_ = value;
}

// -------------------------------------------------------------------

// Sheet_EscortEscort

// repeated .proto_ff.E_EscortEscort E_EscortEscort_List = 1;
inline int Sheet_EscortEscort::e_escortescort_list_size() const {
  return e_escortescort_list_.size();
}
inline void Sheet_EscortEscort::clear_e_escortescort_list() {
  e_escortescort_list_.Clear();
}
inline const ::proto_ff::E_EscortEscort& Sheet_EscortEscort::e_escortescort_list(int index) const {
  return e_escortescort_list_.Get(index);
}
inline ::proto_ff::E_EscortEscort* Sheet_EscortEscort::mutable_e_escortescort_list(int index) {
  return e_escortescort_list_.Mutable(index);
}
inline ::proto_ff::E_EscortEscort* Sheet_EscortEscort::add_e_escortescort_list() {
  return e_escortescort_list_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::proto_ff::E_EscortEscort >&
Sheet_EscortEscort::e_escortescort_list() const {
  return e_escortescort_list_;
}
inline ::google::protobuf::RepeatedPtrField< ::proto_ff::E_EscortEscort >*
Sheet_EscortEscort::mutable_e_escortescort_list() {
  return &e_escortescort_list_;
}

// -------------------------------------------------------------------

// E_EscortChanceEscortDesc

// optional int32 m_chance = 1;
inline bool E_EscortChanceEscortDesc::has_m_chance() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void E_EscortChanceEscortDesc::set_has_m_chance() {
  _has_bits_[0] |= 0x00000001u;
}
inline void E_EscortChanceEscortDesc::clear_has_m_chance() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void E_EscortChanceEscortDesc::clear_m_chance() {
  m_chance_ = 0;
  clear_has_m_chance();
}
inline ::google::protobuf::int32 E_EscortChanceEscortDesc::m_chance() const {
  return m_chance_;
}
inline void E_EscortChanceEscortDesc::set_m_chance(::google::protobuf::int32 value) {
  set_has_m_chance();
  m_chance_ = value;
}

// optional int32 m_ID = 2;
inline bool E_EscortChanceEscortDesc::has_m_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void E_EscortChanceEscortDesc::set_has_m_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void E_EscortChanceEscortDesc::clear_has_m_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void E_EscortChanceEscortDesc::clear_m_id() {
  m_id_ = 0;
  clear_has_m_id();
}
inline ::google::protobuf::int32 E_EscortChanceEscortDesc::m_id() const {
  return m_id_;
}
inline void E_EscortChanceEscortDesc::set_m_id(::google::protobuf::int32 value) {
  set_has_m_id();
  m_id_ = value;
}

// -------------------------------------------------------------------

// E_EscortChance

// optional int32 m_convoyId = 1;
inline bool E_EscortChance::has_m_convoyid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void E_EscortChance::set_has_m_convoyid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void E_EscortChance::clear_has_m_convoyid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void E_EscortChance::clear_m_convoyid() {
  m_convoyid_ = 0;
  clear_has_m_convoyid();
}
inline ::google::protobuf::int32 E_EscortChance::m_convoyid() const {
  return m_convoyid_;
}
inline void E_EscortChance::set_m_convoyid(::google::protobuf::int32 value) {
  set_has_m_convoyid();
  m_convoyid_ = value;
}

// repeated .proto_ff.E_EscortChanceEscortDesc m_escort = 2;
inline int E_EscortChance::m_escort_size() const {
  return m_escort_.size();
}
inline void E_EscortChance::clear_m_escort() {
  m_escort_.Clear();
}
inline const ::proto_ff::E_EscortChanceEscortDesc& E_EscortChance::m_escort(int index) const {
  return m_escort_.Get(index);
}
inline ::proto_ff::E_EscortChanceEscortDesc* E_EscortChance::mutable_m_escort(int index) {
  return m_escort_.Mutable(index);
}
inline ::proto_ff::E_EscortChanceEscortDesc* E_EscortChance::add_m_escort() {
  return m_escort_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::proto_ff::E_EscortChanceEscortDesc >&
E_EscortChance::m_escort() const {
  return m_escort_;
}
inline ::google::protobuf::RepeatedPtrField< ::proto_ff::E_EscortChanceEscortDesc >*
E_EscortChance::mutable_m_escort() {
  return &m_escort_;
}

// -------------------------------------------------------------------

// Sheet_EscortChance

// repeated .proto_ff.E_EscortChance E_EscortChance_List = 1;
inline int Sheet_EscortChance::e_escortchance_list_size() const {
  return e_escortchance_list_.size();
}
inline void Sheet_EscortChance::clear_e_escortchance_list() {
  e_escortchance_list_.Clear();
}
inline const ::proto_ff::E_EscortChance& Sheet_EscortChance::e_escortchance_list(int index) const {
  return e_escortchance_list_.Get(index);
}
inline ::proto_ff::E_EscortChance* Sheet_EscortChance::mutable_e_escortchance_list(int index) {
  return e_escortchance_list_.Mutable(index);
}
inline ::proto_ff::E_EscortChance* Sheet_EscortChance::add_e_escortchance_list() {
  return e_escortchance_list_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::proto_ff::E_EscortChance >&
Sheet_EscortChance::e_escortchance_list() const {
  return e_escortchance_list_;
}
inline ::google::protobuf::RepeatedPtrField< ::proto_ff::E_EscortChance >*
Sheet_EscortChance::mutable_e_escortchance_list() {
  return &e_escortchance_list_;
}

// -------------------------------------------------------------------

// E_EscortRewardRewardDesc

// optional int32 m_num = 1;
inline bool E_EscortRewardRewardDesc::has_m_num() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void E_EscortRewardRewardDesc::set_has_m_num() {
  _has_bits_[0] |= 0x00000001u;
}
inline void E_EscortRewardRewardDesc::clear_has_m_num() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void E_EscortRewardRewardDesc::clear_m_num() {
  m_num_ = 0;
  clear_has_m_num();
}
inline ::google::protobuf::int32 E_EscortRewardRewardDesc::m_num() const {
  return m_num_;
}
inline void E_EscortRewardRewardDesc::set_m_num(::google::protobuf::int32 value) {
  set_has_m_num();
  m_num_ = value;
}

// optional int32 m_item = 2;
inline bool E_EscortRewardRewardDesc::has_m_item() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void E_EscortRewardRewardDesc::set_has_m_item() {
  _has_bits_[0] |= 0x00000002u;
}
inline void E_EscortRewardRewardDesc::clear_has_m_item() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void E_EscortRewardRewardDesc::clear_m_item() {
  m_item_ = 0;
  clear_has_m_item();
}
inline ::google::protobuf::int32 E_EscortRewardRewardDesc::m_item() const {
  return m_item_;
}
inline void E_EscortRewardRewardDesc::set_m_item(::google::protobuf::int32 value) {
  set_has_m_item();
  m_item_ = value;
}

// optional int32 m_ID = 3;
inline bool E_EscortRewardRewardDesc::has_m_id() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void E_EscortRewardRewardDesc::set_has_m_id() {
  _has_bits_[0] |= 0x00000004u;
}
inline void E_EscortRewardRewardDesc::clear_has_m_id() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void E_EscortRewardRewardDesc::clear_m_id() {
  m_id_ = 0;
  clear_has_m_id();
}
inline ::google::protobuf::int32 E_EscortRewardRewardDesc::m_id() const {
  return m_id_;
}
inline void E_EscortRewardRewardDesc::set_m_id(::google::protobuf::int32 value) {
  set_has_m_id();
  m_id_ = value;
}

// -------------------------------------------------------------------

// E_EscortReward

// optional int32 m_lv = 1;
inline bool E_EscortReward::has_m_lv() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void E_EscortReward::set_has_m_lv() {
  _has_bits_[0] |= 0x00000001u;
}
inline void E_EscortReward::clear_has_m_lv() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void E_EscortReward::clear_m_lv() {
  m_lv_ = 0;
  clear_has_m_lv();
}
inline ::google::protobuf::int32 E_EscortReward::m_lv() const {
  return m_lv_;
}
inline void E_EscortReward::set_m_lv(::google::protobuf::int32 value) {
  set_has_m_lv();
  m_lv_ = value;
}

// optional int64 m_exp = 2;
inline bool E_EscortReward::has_m_exp() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void E_EscortReward::set_has_m_exp() {
  _has_bits_[0] |= 0x00000002u;
}
inline void E_EscortReward::clear_has_m_exp() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void E_EscortReward::clear_m_exp() {
  m_exp_ = GOOGLE_LONGLONG(0);
  clear_has_m_exp();
}
inline ::google::protobuf::int64 E_EscortReward::m_exp() const {
  return m_exp_;
}
inline void E_EscortReward::set_m_exp(::google::protobuf::int64 value) {
  set_has_m_exp();
  m_exp_ = value;
}

// repeated .proto_ff.E_EscortRewardRewardDesc m_reward = 3;
inline int E_EscortReward::m_reward_size() const {
  return m_reward_.size();
}
inline void E_EscortReward::clear_m_reward() {
  m_reward_.Clear();
}
inline const ::proto_ff::E_EscortRewardRewardDesc& E_EscortReward::m_reward(int index) const {
  return m_reward_.Get(index);
}
inline ::proto_ff::E_EscortRewardRewardDesc* E_EscortReward::mutable_m_reward(int index) {
  return m_reward_.Mutable(index);
}
inline ::proto_ff::E_EscortRewardRewardDesc* E_EscortReward::add_m_reward() {
  return m_reward_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::proto_ff::E_EscortRewardRewardDesc >&
E_EscortReward::m_reward() const {
  return m_reward_;
}
inline ::google::protobuf::RepeatedPtrField< ::proto_ff::E_EscortRewardRewardDesc >*
E_EscortReward::mutable_m_reward() {
  return &m_reward_;
}

// -------------------------------------------------------------------

// Sheet_EscortReward

// repeated .proto_ff.E_EscortReward E_EscortReward_List = 1;
inline int Sheet_EscortReward::e_escortreward_list_size() const {
  return e_escortreward_list_.size();
}
inline void Sheet_EscortReward::clear_e_escortreward_list() {
  e_escortreward_list_.Clear();
}
inline const ::proto_ff::E_EscortReward& Sheet_EscortReward::e_escortreward_list(int index) const {
  return e_escortreward_list_.Get(index);
}
inline ::proto_ff::E_EscortReward* Sheet_EscortReward::mutable_e_escortreward_list(int index) {
  return e_escortreward_list_.Mutable(index);
}
inline ::proto_ff::E_EscortReward* Sheet_EscortReward::add_e_escortreward_list() {
  return e_escortreward_list_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::proto_ff::E_EscortReward >&
Sheet_EscortReward::e_escortreward_list() const {
  return e_escortreward_list_;
}
inline ::google::protobuf::RepeatedPtrField< ::proto_ff::E_EscortReward >*
Sheet_EscortReward::mutable_e_escortreward_list() {
  return &e_escortreward_list_;
}

// -------------------------------------------------------------------

// E_EscortConst

// optional int32 m_id = 1;
inline bool E_EscortConst::has_m_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void E_EscortConst::set_has_m_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void E_EscortConst::clear_has_m_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void E_EscortConst::clear_m_id() {
  m_id_ = 0;
  clear_has_m_id();
}
inline ::google::protobuf::int32 E_EscortConst::m_id() const {
  return m_id_;
}
inline void E_EscortConst::set_m_id(::google::protobuf::int32 value) {
  set_has_m_id();
  m_id_ = value;
}

// optional int32 m_tokenId = 2;
inline bool E_EscortConst::has_m_tokenid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void E_EscortConst::set_has_m_tokenid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void E_EscortConst::clear_has_m_tokenid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void E_EscortConst::clear_m_tokenid() {
  m_tokenid_ = 0;
  clear_has_m_tokenid();
}
inline ::google::protobuf::int32 E_EscortConst::m_tokenid() const {
  return m_tokenid_;
}
inline void E_EscortConst::set_m_tokenid(::google::protobuf::int32 value) {
  set_has_m_tokenid();
  m_tokenid_ = value;
}

// optional int32 m_tokenNumber = 3;
inline bool E_EscortConst::has_m_tokennumber() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void E_EscortConst::set_has_m_tokennumber() {
  _has_bits_[0] |= 0x00000004u;
}
inline void E_EscortConst::clear_has_m_tokennumber() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void E_EscortConst::clear_m_tokennumber() {
  m_tokennumber_ = 0;
  clear_has_m_tokennumber();
}
inline ::google::protobuf::int32 E_EscortConst::m_tokennumber() const {
  return m_tokennumber_;
}
inline void E_EscortConst::set_m_tokennumber(::google::protobuf::int32 value) {
  set_has_m_tokennumber();
  m_tokennumber_ = value;
}

// optional int32 m_dayTime = 4;
inline bool E_EscortConst::has_m_daytime() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void E_EscortConst::set_has_m_daytime() {
  _has_bits_[0] |= 0x00000008u;
}
inline void E_EscortConst::clear_has_m_daytime() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void E_EscortConst::clear_m_daytime() {
  m_daytime_ = 0;
  clear_has_m_daytime();
}
inline ::google::protobuf::int32 E_EscortConst::m_daytime() const {
  return m_daytime_;
}
inline void E_EscortConst::set_m_daytime(::google::protobuf::int32 value) {
  set_has_m_daytime();
  m_daytime_ = value;
}

// optional int32 m_freeNum = 5;
inline bool E_EscortConst::has_m_freenum() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void E_EscortConst::set_has_m_freenum() {
  _has_bits_[0] |= 0x00000010u;
}
inline void E_EscortConst::clear_has_m_freenum() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void E_EscortConst::clear_m_freenum() {
  m_freenum_ = 0;
  clear_has_m_freenum();
}
inline ::google::protobuf::int32 E_EscortConst::m_freenum() const {
  return m_freenum_;
}
inline void E_EscortConst::set_m_freenum(::google::protobuf::int32 value) {
  set_has_m_freenum();
  m_freenum_ = value;
}

// optional int32 m_mapId = 6;
inline bool E_EscortConst::has_m_mapid() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void E_EscortConst::set_has_m_mapid() {
  _has_bits_[0] |= 0x00000020u;
}
inline void E_EscortConst::clear_has_m_mapid() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void E_EscortConst::clear_m_mapid() {
  m_mapid_ = 0;
  clear_has_m_mapid();
}
inline ::google::protobuf::int32 E_EscortConst::m_mapid() const {
  return m_mapid_;
}
inline void E_EscortConst::set_m_mapid(::google::protobuf::int32 value) {
  set_has_m_mapid();
  m_mapid_ = value;
}

// optional int32 m_startNpcID = 7;
inline bool E_EscortConst::has_m_startnpcid() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void E_EscortConst::set_has_m_startnpcid() {
  _has_bits_[0] |= 0x00000040u;
}
inline void E_EscortConst::clear_has_m_startnpcid() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void E_EscortConst::clear_m_startnpcid() {
  m_startnpcid_ = 0;
  clear_has_m_startnpcid();
}
inline ::google::protobuf::int32 E_EscortConst::m_startnpcid() const {
  return m_startnpcid_;
}
inline void E_EscortConst::set_m_startnpcid(::google::protobuf::int32 value) {
  set_has_m_startnpcid();
  m_startnpcid_ = value;
}

// optional int32 m_startNpcPointID = 8;
inline bool E_EscortConst::has_m_startnpcpointid() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void E_EscortConst::set_has_m_startnpcpointid() {
  _has_bits_[0] |= 0x00000080u;
}
inline void E_EscortConst::clear_has_m_startnpcpointid() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void E_EscortConst::clear_m_startnpcpointid() {
  m_startnpcpointid_ = 0;
  clear_has_m_startnpcpointid();
}
inline ::google::protobuf::int32 E_EscortConst::m_startnpcpointid() const {
  return m_startnpcpointid_;
}
inline void E_EscortConst::set_m_startnpcpointid(::google::protobuf::int32 value) {
  set_has_m_startnpcpointid();
  m_startnpcpointid_ = value;
}

// optional int32 m_overNpcID = 9;
inline bool E_EscortConst::has_m_overnpcid() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void E_EscortConst::set_has_m_overnpcid() {
  _has_bits_[0] |= 0x00000100u;
}
inline void E_EscortConst::clear_has_m_overnpcid() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void E_EscortConst::clear_m_overnpcid() {
  m_overnpcid_ = 0;
  clear_has_m_overnpcid();
}
inline ::google::protobuf::int32 E_EscortConst::m_overnpcid() const {
  return m_overnpcid_;
}
inline void E_EscortConst::set_m_overnpcid(::google::protobuf::int32 value) {
  set_has_m_overnpcid();
  m_overnpcid_ = value;
}

// optional int32 m_activityID = 10;
inline bool E_EscortConst::has_m_activityid() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void E_EscortConst::set_has_m_activityid() {
  _has_bits_[0] |= 0x00000200u;
}
inline void E_EscortConst::clear_has_m_activityid() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void E_EscortConst::clear_m_activityid() {
  m_activityid_ = 0;
  clear_has_m_activityid();
}
inline ::google::protobuf::int32 E_EscortConst::m_activityid() const {
  return m_activityid_;
}
inline void E_EscortConst::set_m_activityid(::google::protobuf::int32 value) {
  set_has_m_activityid();
  m_activityid_ = value;
}

// optional int32 m_taskID = 11;
inline bool E_EscortConst::has_m_taskid() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void E_EscortConst::set_has_m_taskid() {
  _has_bits_[0] |= 0x00000400u;
}
inline void E_EscortConst::clear_has_m_taskid() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void E_EscortConst::clear_m_taskid() {
  m_taskid_ = 0;
  clear_has_m_taskid();
}
inline ::google::protobuf::int32 E_EscortConst::m_taskid() const {
  return m_taskid_;
}
inline void E_EscortConst::set_m_taskid(::google::protobuf::int32 value) {
  set_has_m_taskid();
  m_taskid_ = value;
}

// optional int32 m_DistanceA = 12;
inline bool E_EscortConst::has_m_distancea() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void E_EscortConst::set_has_m_distancea() {
  _has_bits_[0] |= 0x00000800u;
}
inline void E_EscortConst::clear_has_m_distancea() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void E_EscortConst::clear_m_distancea() {
  m_distancea_ = 0;
  clear_has_m_distancea();
}
inline ::google::protobuf::int32 E_EscortConst::m_distancea() const {
  return m_distancea_;
}
inline void E_EscortConst::set_m_distancea(::google::protobuf::int32 value) {
  set_has_m_distancea();
  m_distancea_ = value;
}

// optional int32 m_DistanceB = 13;
inline bool E_EscortConst::has_m_distanceb() const {
  return (_has_bits_[0] & 0x00001000u) != 0;
}
inline void E_EscortConst::set_has_m_distanceb() {
  _has_bits_[0] |= 0x00001000u;
}
inline void E_EscortConst::clear_has_m_distanceb() {
  _has_bits_[0] &= ~0x00001000u;
}
inline void E_EscortConst::clear_m_distanceb() {
  m_distanceb_ = 0;
  clear_has_m_distanceb();
}
inline ::google::protobuf::int32 E_EscortConst::m_distanceb() const {
  return m_distanceb_;
}
inline void E_EscortConst::set_m_distanceb(::google::protobuf::int32 value) {
  set_has_m_distanceb();
  m_distanceb_ = value;
}

// optional int32 m_DistanceC = 14;
inline bool E_EscortConst::has_m_distancec() const {
  return (_has_bits_[0] & 0x00002000u) != 0;
}
inline void E_EscortConst::set_has_m_distancec() {
  _has_bits_[0] |= 0x00002000u;
}
inline void E_EscortConst::clear_has_m_distancec() {
  _has_bits_[0] &= ~0x00002000u;
}
inline void E_EscortConst::clear_m_distancec() {
  m_distancec_ = 0;
  clear_has_m_distancec();
}
inline ::google::protobuf::int32 E_EscortConst::m_distancec() const {
  return m_distancec_;
}
inline void E_EscortConst::set_m_distancec(::google::protobuf::int32 value) {
  set_has_m_distancec();
  m_distancec_ = value;
}

// optional int32 m_timeLimit = 15;
inline bool E_EscortConst::has_m_timelimit() const {
  return (_has_bits_[0] & 0x00004000u) != 0;
}
inline void E_EscortConst::set_has_m_timelimit() {
  _has_bits_[0] |= 0x00004000u;
}
inline void E_EscortConst::clear_has_m_timelimit() {
  _has_bits_[0] &= ~0x00004000u;
}
inline void E_EscortConst::clear_m_timelimit() {
  m_timelimit_ = 0;
  clear_has_m_timelimit();
}
inline ::google::protobuf::int32 E_EscortConst::m_timelimit() const {
  return m_timelimit_;
}
inline void E_EscortConst::set_m_timelimit(::google::protobuf::int32 value) {
  set_has_m_timelimit();
  m_timelimit_ = value;
}

// -------------------------------------------------------------------

// Sheet_EscortConst

// repeated .proto_ff.E_EscortConst E_EscortConst_List = 1;
inline int Sheet_EscortConst::e_escortconst_list_size() const {
  return e_escortconst_list_.size();
}
inline void Sheet_EscortConst::clear_e_escortconst_list() {
  e_escortconst_list_.Clear();
}
inline const ::proto_ff::E_EscortConst& Sheet_EscortConst::e_escortconst_list(int index) const {
  return e_escortconst_list_.Get(index);
}
inline ::proto_ff::E_EscortConst* Sheet_EscortConst::mutable_e_escortconst_list(int index) {
  return e_escortconst_list_.Mutable(index);
}
inline ::proto_ff::E_EscortConst* Sheet_EscortConst::add_e_escortconst_list() {
  return e_escortconst_list_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::proto_ff::E_EscortConst >&
Sheet_EscortConst::e_escortconst_list() const {
  return e_escortconst_list_;
}
inline ::google::protobuf::RepeatedPtrField< ::proto_ff::E_EscortConst >*
Sheet_EscortConst::mutable_e_escortconst_list() {
  return &e_escortconst_list_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto_ff

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_E_5fEscort_2eproto__INCLUDED
