// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: E_Path.proto

#ifndef PROTOBUF_E_5fPath_2eproto__INCLUDED
#define PROTOBUF_E_5fPath_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "yd_fieldoptions.pb.h"
// @@protoc_insertion_point(includes)

namespace proto_ff {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_E_5fPath_2eproto();
void protobuf_AssignDesc_E_5fPath_2eproto();
void protobuf_ShutdownFile_E_5fPath_2eproto();

class E_PathPath;
class Sheet_PathPath;

// ===================================================================

class E_PathPath : public ::google::protobuf::Message {
 public:
  E_PathPath();
  virtual ~E_PathPath();

  E_PathPath(const E_PathPath& from);

  inline E_PathPath& operator=(const E_PathPath& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const E_PathPath& default_instance();

  void Swap(E_PathPath* other);

  // implements Message ----------------------------------------------

  E_PathPath* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const E_PathPath& from);
  void MergeFrom(const E_PathPath& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 m_id = 1;
  inline bool has_m_id() const;
  inline void clear_m_id();
  static const int kMIdFieldNumber = 1;
  inline ::google::protobuf::int64 m_id() const;
  inline void set_m_id(::google::protobuf::int64 value);

  // optional int64 m_belongtosceneid = 2;
  inline bool has_m_belongtosceneid() const;
  inline void clear_m_belongtosceneid();
  static const int kMBelongtosceneidFieldNumber = 2;
  inline ::google::protobuf::int64 m_belongtosceneid() const;
  inline void set_m_belongtosceneid(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:proto_ff.E_PathPath)
 private:
  inline void set_has_m_id();
  inline void clear_has_m_id();
  inline void set_has_m_belongtosceneid();
  inline void clear_has_m_belongtosceneid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int64 m_id_;
  ::google::protobuf::int64 m_belongtosceneid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_E_5fPath_2eproto();
  friend void protobuf_AssignDesc_E_5fPath_2eproto();
  friend void protobuf_ShutdownFile_E_5fPath_2eproto();

  void InitAsDefaultInstance();
  static E_PathPath* default_instance_;
};
// -------------------------------------------------------------------

class Sheet_PathPath : public ::google::protobuf::Message {
 public:
  Sheet_PathPath();
  virtual ~Sheet_PathPath();

  Sheet_PathPath(const Sheet_PathPath& from);

  inline Sheet_PathPath& operator=(const Sheet_PathPath& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Sheet_PathPath& default_instance();

  void Swap(Sheet_PathPath* other);

  // implements Message ----------------------------------------------

  Sheet_PathPath* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Sheet_PathPath& from);
  void MergeFrom(const Sheet_PathPath& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .proto_ff.E_PathPath E_PathPath_List = 1;
  inline int e_pathpath_list_size() const;
  inline void clear_e_pathpath_list();
  static const int kEPathPathListFieldNumber = 1;
  inline const ::proto_ff::E_PathPath& e_pathpath_list(int index) const;
  inline ::proto_ff::E_PathPath* mutable_e_pathpath_list(int index);
  inline ::proto_ff::E_PathPath* add_e_pathpath_list();
  inline const ::google::protobuf::RepeatedPtrField< ::proto_ff::E_PathPath >&
      e_pathpath_list() const;
  inline ::google::protobuf::RepeatedPtrField< ::proto_ff::E_PathPath >*
      mutable_e_pathpath_list();

  // @@protoc_insertion_point(class_scope:proto_ff.Sheet_PathPath)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::proto_ff::E_PathPath > e_pathpath_list_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_E_5fPath_2eproto();
  friend void protobuf_AssignDesc_E_5fPath_2eproto();
  friend void protobuf_ShutdownFile_E_5fPath_2eproto();

  void InitAsDefaultInstance();
  static Sheet_PathPath* default_instance_;
};
// ===================================================================


// ===================================================================

// E_PathPath

// optional int64 m_id = 1;
inline bool E_PathPath::has_m_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void E_PathPath::set_has_m_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void E_PathPath::clear_has_m_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void E_PathPath::clear_m_id() {
  m_id_ = GOOGLE_LONGLONG(0);
  clear_has_m_id();
}
inline ::google::protobuf::int64 E_PathPath::m_id() const {
  return m_id_;
}
inline void E_PathPath::set_m_id(::google::protobuf::int64 value) {
  set_has_m_id();
  m_id_ = value;
}

// optional int64 m_belongtosceneid = 2;
inline bool E_PathPath::has_m_belongtosceneid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void E_PathPath::set_has_m_belongtosceneid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void E_PathPath::clear_has_m_belongtosceneid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void E_PathPath::clear_m_belongtosceneid() {
  m_belongtosceneid_ = GOOGLE_LONGLONG(0);
  clear_has_m_belongtosceneid();
}
inline ::google::protobuf::int64 E_PathPath::m_belongtosceneid() const {
  return m_belongtosceneid_;
}
inline void E_PathPath::set_m_belongtosceneid(::google::protobuf::int64 value) {
  set_has_m_belongtosceneid();
  m_belongtosceneid_ = value;
}

// -------------------------------------------------------------------

// Sheet_PathPath

// repeated .proto_ff.E_PathPath E_PathPath_List = 1;
inline int Sheet_PathPath::e_pathpath_list_size() const {
  return e_pathpath_list_.size();
}
inline void Sheet_PathPath::clear_e_pathpath_list() {
  e_pathpath_list_.Clear();
}
inline const ::proto_ff::E_PathPath& Sheet_PathPath::e_pathpath_list(int index) const {
  return e_pathpath_list_.Get(index);
}
inline ::proto_ff::E_PathPath* Sheet_PathPath::mutable_e_pathpath_list(int index) {
  return e_pathpath_list_.Mutable(index);
}
inline ::proto_ff::E_PathPath* Sheet_PathPath::add_e_pathpath_list() {
  return e_pathpath_list_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::proto_ff::E_PathPath >&
Sheet_PathPath::e_pathpath_list() const {
  return e_pathpath_list_;
}
inline ::google::protobuf::RepeatedPtrField< ::proto_ff::E_PathPath >*
Sheet_PathPath::mutable_e_pathpath_list() {
  return &e_pathpath_list_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto_ff

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_E_5fPath_2eproto__INCLUDED
