// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: E_Personalshop.proto

#ifndef PROTOBUF_E_5fPersonalshop_2eproto__INCLUDED
#define PROTOBUF_E_5fPersonalshop_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "yd_fieldoptions.pb.h"
// @@protoc_insertion_point(includes)

namespace proto_ff {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_E_5fPersonalshop_2eproto();
void protobuf_AssignDesc_E_5fPersonalshop_2eproto();
void protobuf_ShutdownFile_E_5fPersonalshop_2eproto();

class E_PersonalshopShopitems;
class Sheet_PersonalshopShopitems;
class E_PersonalshopShops;
class Sheet_PersonalshopShops;

// ===================================================================

class E_PersonalshopShopitems : public ::google::protobuf::Message {
 public:
  E_PersonalshopShopitems();
  virtual ~E_PersonalshopShopitems();

  E_PersonalshopShopitems(const E_PersonalshopShopitems& from);

  inline E_PersonalshopShopitems& operator=(const E_PersonalshopShopitems& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const E_PersonalshopShopitems& default_instance();

  void Swap(E_PersonalshopShopitems* other);

  // implements Message ----------------------------------------------

  E_PersonalshopShopitems* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const E_PersonalshopShopitems& from);
  void MergeFrom(const E_PersonalshopShopitems& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 m_id = 1;
  inline bool has_m_id() const;
  inline void clear_m_id();
  static const int kMIdFieldNumber = 1;
  inline ::google::protobuf::int32 m_id() const;
  inline void set_m_id(::google::protobuf::int32 value);

  // optional int32 m_shopid = 2;
  inline bool has_m_shopid() const;
  inline void clear_m_shopid();
  static const int kMShopidFieldNumber = 2;
  inline ::google::protobuf::int32 m_shopid() const;
  inline void set_m_shopid(::google::protobuf::int32 value);

  // optional int32 m_itemid = 3;
  inline bool has_m_itemid() const;
  inline void clear_m_itemid();
  static const int kMItemidFieldNumber = 3;
  inline ::google::protobuf::int32 m_itemid() const;
  inline void set_m_itemid(::google::protobuf::int32 value);

  // optional int32 m_amount = 4;
  inline bool has_m_amount() const;
  inline void clear_m_amount();
  static const int kMAmountFieldNumber = 4;
  inline ::google::protobuf::int32 m_amount() const;
  inline void set_m_amount(::google::protobuf::int32 value);

  // optional int32 m_currency = 5;
  inline bool has_m_currency() const;
  inline void clear_m_currency();
  static const int kMCurrencyFieldNumber = 5;
  inline ::google::protobuf::int32 m_currency() const;
  inline void set_m_currency(::google::protobuf::int32 value);

  // optional int32 m_price = 6;
  inline bool has_m_price() const;
  inline void clear_m_price();
  static const int kMPriceFieldNumber = 6;
  inline ::google::protobuf::int32 m_price() const;
  inline void set_m_price(::google::protobuf::int32 value);

  // optional int32 m_discount = 7;
  inline bool has_m_discount() const;
  inline void clear_m_discount();
  static const int kMDiscountFieldNumber = 7;
  inline ::google::protobuf::int32 m_discount() const;
  inline void set_m_discount(::google::protobuf::int32 value);

  // optional int32 m_lvlimit = 8;
  inline bool has_m_lvlimit() const;
  inline void clear_m_lvlimit();
  static const int kMLvlimitFieldNumber = 8;
  inline ::google::protobuf::int32 m_lvlimit() const;
  inline void set_m_lvlimit(::google::protobuf::int32 value);

  // optional int32 m_weight = 9;
  inline bool has_m_weight() const;
  inline void clear_m_weight();
  static const int kMWeightFieldNumber = 9;
  inline ::google::protobuf::int32 m_weight() const;
  inline void set_m_weight(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:proto_ff.E_PersonalshopShopitems)
 private:
  inline void set_has_m_id();
  inline void clear_has_m_id();
  inline void set_has_m_shopid();
  inline void clear_has_m_shopid();
  inline void set_has_m_itemid();
  inline void clear_has_m_itemid();
  inline void set_has_m_amount();
  inline void clear_has_m_amount();
  inline void set_has_m_currency();
  inline void clear_has_m_currency();
  inline void set_has_m_price();
  inline void clear_has_m_price();
  inline void set_has_m_discount();
  inline void clear_has_m_discount();
  inline void set_has_m_lvlimit();
  inline void clear_has_m_lvlimit();
  inline void set_has_m_weight();
  inline void clear_has_m_weight();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 m_id_;
  ::google::protobuf::int32 m_shopid_;
  ::google::protobuf::int32 m_itemid_;
  ::google::protobuf::int32 m_amount_;
  ::google::protobuf::int32 m_currency_;
  ::google::protobuf::int32 m_price_;
  ::google::protobuf::int32 m_discount_;
  ::google::protobuf::int32 m_lvlimit_;
  ::google::protobuf::int32 m_weight_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(9 + 31) / 32];

  friend void  protobuf_AddDesc_E_5fPersonalshop_2eproto();
  friend void protobuf_AssignDesc_E_5fPersonalshop_2eproto();
  friend void protobuf_ShutdownFile_E_5fPersonalshop_2eproto();

  void InitAsDefaultInstance();
  static E_PersonalshopShopitems* default_instance_;
};
// -------------------------------------------------------------------

class Sheet_PersonalshopShopitems : public ::google::protobuf::Message {
 public:
  Sheet_PersonalshopShopitems();
  virtual ~Sheet_PersonalshopShopitems();

  Sheet_PersonalshopShopitems(const Sheet_PersonalshopShopitems& from);

  inline Sheet_PersonalshopShopitems& operator=(const Sheet_PersonalshopShopitems& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Sheet_PersonalshopShopitems& default_instance();

  void Swap(Sheet_PersonalshopShopitems* other);

  // implements Message ----------------------------------------------

  Sheet_PersonalshopShopitems* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Sheet_PersonalshopShopitems& from);
  void MergeFrom(const Sheet_PersonalshopShopitems& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .proto_ff.E_PersonalshopShopitems E_PersonalshopShopitems_List = 1;
  inline int e_personalshopshopitems_list_size() const;
  inline void clear_e_personalshopshopitems_list();
  static const int kEPersonalshopShopitemsListFieldNumber = 1;
  inline const ::proto_ff::E_PersonalshopShopitems& e_personalshopshopitems_list(int index) const;
  inline ::proto_ff::E_PersonalshopShopitems* mutable_e_personalshopshopitems_list(int index);
  inline ::proto_ff::E_PersonalshopShopitems* add_e_personalshopshopitems_list();
  inline const ::google::protobuf::RepeatedPtrField< ::proto_ff::E_PersonalshopShopitems >&
      e_personalshopshopitems_list() const;
  inline ::google::protobuf::RepeatedPtrField< ::proto_ff::E_PersonalshopShopitems >*
      mutable_e_personalshopshopitems_list();

  // @@protoc_insertion_point(class_scope:proto_ff.Sheet_PersonalshopShopitems)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::proto_ff::E_PersonalshopShopitems > e_personalshopshopitems_list_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_E_5fPersonalshop_2eproto();
  friend void protobuf_AssignDesc_E_5fPersonalshop_2eproto();
  friend void protobuf_ShutdownFile_E_5fPersonalshop_2eproto();

  void InitAsDefaultInstance();
  static Sheet_PersonalshopShopitems* default_instance_;
};
// -------------------------------------------------------------------

class E_PersonalshopShops : public ::google::protobuf::Message {
 public:
  E_PersonalshopShops();
  virtual ~E_PersonalshopShops();

  E_PersonalshopShops(const E_PersonalshopShops& from);

  inline E_PersonalshopShops& operator=(const E_PersonalshopShops& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const E_PersonalshopShops& default_instance();

  void Swap(E_PersonalshopShops* other);

  // implements Message ----------------------------------------------

  E_PersonalshopShops* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const E_PersonalshopShops& from);
  void MergeFrom(const E_PersonalshopShops& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 m_id = 1;
  inline bool has_m_id() const;
  inline void clear_m_id();
  static const int kMIdFieldNumber = 1;
  inline ::google::protobuf::int32 m_id() const;
  inline void set_m_id(::google::protobuf::int32 value);

  // optional int32 m_keeptime = 2;
  inline bool has_m_keeptime() const;
  inline void clear_m_keeptime();
  static const int kMKeeptimeFieldNumber = 2;
  inline ::google::protobuf::int32 m_keeptime() const;
  inline void set_m_keeptime(::google::protobuf::int32 value);

  // optional int32 m_freetimes = 3;
  inline bool has_m_freetimes() const;
  inline void clear_m_freetimes();
  static const int kMFreetimesFieldNumber = 3;
  inline ::google::protobuf::int32 m_freetimes() const;
  inline void set_m_freetimes(::google::protobuf::int32 value);

  // optional int32 m_refreshmoney = 4;
  inline bool has_m_refreshmoney() const;
  inline void clear_m_refreshmoney();
  static const int kMRefreshmoneyFieldNumber = 4;
  inline ::google::protobuf::int32 m_refreshmoney() const;
  inline void set_m_refreshmoney(::google::protobuf::int32 value);

  // optional int32 m_refreshprice = 5;
  inline bool has_m_refreshprice() const;
  inline void clear_m_refreshprice();
  static const int kMRefreshpriceFieldNumber = 5;
  inline ::google::protobuf::int32 m_refreshprice() const;
  inline void set_m_refreshprice(::google::protobuf::int32 value);

  // optional int32 m_salelistcount = 6;
  inline bool has_m_salelistcount() const;
  inline void clear_m_salelistcount();
  static const int kMSalelistcountFieldNumber = 6;
  inline ::google::protobuf::int32 m_salelistcount() const;
  inline void set_m_salelistcount(::google::protobuf::int32 value);

  // optional int32 m_addtype = 7;
  inline bool has_m_addtype() const;
  inline void clear_m_addtype();
  static const int kMAddtypeFieldNumber = 7;
  inline ::google::protobuf::int32 m_addtype() const;
  inline void set_m_addtype(::google::protobuf::int32 value);

  // optional int32 m_addtypevalue = 8;
  inline bool has_m_addtypevalue() const;
  inline void clear_m_addtypevalue();
  static const int kMAddtypevalueFieldNumber = 8;
  inline ::google::protobuf::int32 m_addtypevalue() const;
  inline void set_m_addtypevalue(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:proto_ff.E_PersonalshopShops)
 private:
  inline void set_has_m_id();
  inline void clear_has_m_id();
  inline void set_has_m_keeptime();
  inline void clear_has_m_keeptime();
  inline void set_has_m_freetimes();
  inline void clear_has_m_freetimes();
  inline void set_has_m_refreshmoney();
  inline void clear_has_m_refreshmoney();
  inline void set_has_m_refreshprice();
  inline void clear_has_m_refreshprice();
  inline void set_has_m_salelistcount();
  inline void clear_has_m_salelistcount();
  inline void set_has_m_addtype();
  inline void clear_has_m_addtype();
  inline void set_has_m_addtypevalue();
  inline void clear_has_m_addtypevalue();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 m_id_;
  ::google::protobuf::int32 m_keeptime_;
  ::google::protobuf::int32 m_freetimes_;
  ::google::protobuf::int32 m_refreshmoney_;
  ::google::protobuf::int32 m_refreshprice_;
  ::google::protobuf::int32 m_salelistcount_;
  ::google::protobuf::int32 m_addtype_;
  ::google::protobuf::int32 m_addtypevalue_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(8 + 31) / 32];

  friend void  protobuf_AddDesc_E_5fPersonalshop_2eproto();
  friend void protobuf_AssignDesc_E_5fPersonalshop_2eproto();
  friend void protobuf_ShutdownFile_E_5fPersonalshop_2eproto();

  void InitAsDefaultInstance();
  static E_PersonalshopShops* default_instance_;
};
// -------------------------------------------------------------------

class Sheet_PersonalshopShops : public ::google::protobuf::Message {
 public:
  Sheet_PersonalshopShops();
  virtual ~Sheet_PersonalshopShops();

  Sheet_PersonalshopShops(const Sheet_PersonalshopShops& from);

  inline Sheet_PersonalshopShops& operator=(const Sheet_PersonalshopShops& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Sheet_PersonalshopShops& default_instance();

  void Swap(Sheet_PersonalshopShops* other);

  // implements Message ----------------------------------------------

  Sheet_PersonalshopShops* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Sheet_PersonalshopShops& from);
  void MergeFrom(const Sheet_PersonalshopShops& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .proto_ff.E_PersonalshopShops E_PersonalshopShops_List = 1;
  inline int e_personalshopshops_list_size() const;
  inline void clear_e_personalshopshops_list();
  static const int kEPersonalshopShopsListFieldNumber = 1;
  inline const ::proto_ff::E_PersonalshopShops& e_personalshopshops_list(int index) const;
  inline ::proto_ff::E_PersonalshopShops* mutable_e_personalshopshops_list(int index);
  inline ::proto_ff::E_PersonalshopShops* add_e_personalshopshops_list();
  inline const ::google::protobuf::RepeatedPtrField< ::proto_ff::E_PersonalshopShops >&
      e_personalshopshops_list() const;
  inline ::google::protobuf::RepeatedPtrField< ::proto_ff::E_PersonalshopShops >*
      mutable_e_personalshopshops_list();

  // @@protoc_insertion_point(class_scope:proto_ff.Sheet_PersonalshopShops)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::proto_ff::E_PersonalshopShops > e_personalshopshops_list_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_E_5fPersonalshop_2eproto();
  friend void protobuf_AssignDesc_E_5fPersonalshop_2eproto();
  friend void protobuf_ShutdownFile_E_5fPersonalshop_2eproto();

  void InitAsDefaultInstance();
  static Sheet_PersonalshopShops* default_instance_;
};
// ===================================================================


// ===================================================================

// E_PersonalshopShopitems

// optional int32 m_id = 1;
inline bool E_PersonalshopShopitems::has_m_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void E_PersonalshopShopitems::set_has_m_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void E_PersonalshopShopitems::clear_has_m_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void E_PersonalshopShopitems::clear_m_id() {
  m_id_ = 0;
  clear_has_m_id();
}
inline ::google::protobuf::int32 E_PersonalshopShopitems::m_id() const {
  return m_id_;
}
inline void E_PersonalshopShopitems::set_m_id(::google::protobuf::int32 value) {
  set_has_m_id();
  m_id_ = value;
}

// optional int32 m_shopid = 2;
inline bool E_PersonalshopShopitems::has_m_shopid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void E_PersonalshopShopitems::set_has_m_shopid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void E_PersonalshopShopitems::clear_has_m_shopid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void E_PersonalshopShopitems::clear_m_shopid() {
  m_shopid_ = 0;
  clear_has_m_shopid();
}
inline ::google::protobuf::int32 E_PersonalshopShopitems::m_shopid() const {
  return m_shopid_;
}
inline void E_PersonalshopShopitems::set_m_shopid(::google::protobuf::int32 value) {
  set_has_m_shopid();
  m_shopid_ = value;
}

// optional int32 m_itemid = 3;
inline bool E_PersonalshopShopitems::has_m_itemid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void E_PersonalshopShopitems::set_has_m_itemid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void E_PersonalshopShopitems::clear_has_m_itemid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void E_PersonalshopShopitems::clear_m_itemid() {
  m_itemid_ = 0;
  clear_has_m_itemid();
}
inline ::google::protobuf::int32 E_PersonalshopShopitems::m_itemid() const {
  return m_itemid_;
}
inline void E_PersonalshopShopitems::set_m_itemid(::google::protobuf::int32 value) {
  set_has_m_itemid();
  m_itemid_ = value;
}

// optional int32 m_amount = 4;
inline bool E_PersonalshopShopitems::has_m_amount() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void E_PersonalshopShopitems::set_has_m_amount() {
  _has_bits_[0] |= 0x00000008u;
}
inline void E_PersonalshopShopitems::clear_has_m_amount() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void E_PersonalshopShopitems::clear_m_amount() {
  m_amount_ = 0;
  clear_has_m_amount();
}
inline ::google::protobuf::int32 E_PersonalshopShopitems::m_amount() const {
  return m_amount_;
}
inline void E_PersonalshopShopitems::set_m_amount(::google::protobuf::int32 value) {
  set_has_m_amount();
  m_amount_ = value;
}

// optional int32 m_currency = 5;
inline bool E_PersonalshopShopitems::has_m_currency() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void E_PersonalshopShopitems::set_has_m_currency() {
  _has_bits_[0] |= 0x00000010u;
}
inline void E_PersonalshopShopitems::clear_has_m_currency() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void E_PersonalshopShopitems::clear_m_currency() {
  m_currency_ = 0;
  clear_has_m_currency();
}
inline ::google::protobuf::int32 E_PersonalshopShopitems::m_currency() const {
  return m_currency_;
}
inline void E_PersonalshopShopitems::set_m_currency(::google::protobuf::int32 value) {
  set_has_m_currency();
  m_currency_ = value;
}

// optional int32 m_price = 6;
inline bool E_PersonalshopShopitems::has_m_price() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void E_PersonalshopShopitems::set_has_m_price() {
  _has_bits_[0] |= 0x00000020u;
}
inline void E_PersonalshopShopitems::clear_has_m_price() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void E_PersonalshopShopitems::clear_m_price() {
  m_price_ = 0;
  clear_has_m_price();
}
inline ::google::protobuf::int32 E_PersonalshopShopitems::m_price() const {
  return m_price_;
}
inline void E_PersonalshopShopitems::set_m_price(::google::protobuf::int32 value) {
  set_has_m_price();
  m_price_ = value;
}

// optional int32 m_discount = 7;
inline bool E_PersonalshopShopitems::has_m_discount() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void E_PersonalshopShopitems::set_has_m_discount() {
  _has_bits_[0] |= 0x00000040u;
}
inline void E_PersonalshopShopitems::clear_has_m_discount() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void E_PersonalshopShopitems::clear_m_discount() {
  m_discount_ = 0;
  clear_has_m_discount();
}
inline ::google::protobuf::int32 E_PersonalshopShopitems::m_discount() const {
  return m_discount_;
}
inline void E_PersonalshopShopitems::set_m_discount(::google::protobuf::int32 value) {
  set_has_m_discount();
  m_discount_ = value;
}

// optional int32 m_lvlimit = 8;
inline bool E_PersonalshopShopitems::has_m_lvlimit() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void E_PersonalshopShopitems::set_has_m_lvlimit() {
  _has_bits_[0] |= 0x00000080u;
}
inline void E_PersonalshopShopitems::clear_has_m_lvlimit() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void E_PersonalshopShopitems::clear_m_lvlimit() {
  m_lvlimit_ = 0;
  clear_has_m_lvlimit();
}
inline ::google::protobuf::int32 E_PersonalshopShopitems::m_lvlimit() const {
  return m_lvlimit_;
}
inline void E_PersonalshopShopitems::set_m_lvlimit(::google::protobuf::int32 value) {
  set_has_m_lvlimit();
  m_lvlimit_ = value;
}

// optional int32 m_weight = 9;
inline bool E_PersonalshopShopitems::has_m_weight() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void E_PersonalshopShopitems::set_has_m_weight() {
  _has_bits_[0] |= 0x00000100u;
}
inline void E_PersonalshopShopitems::clear_has_m_weight() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void E_PersonalshopShopitems::clear_m_weight() {
  m_weight_ = 0;
  clear_has_m_weight();
}
inline ::google::protobuf::int32 E_PersonalshopShopitems::m_weight() const {
  return m_weight_;
}
inline void E_PersonalshopShopitems::set_m_weight(::google::protobuf::int32 value) {
  set_has_m_weight();
  m_weight_ = value;
}

// -------------------------------------------------------------------

// Sheet_PersonalshopShopitems

// repeated .proto_ff.E_PersonalshopShopitems E_PersonalshopShopitems_List = 1;
inline int Sheet_PersonalshopShopitems::e_personalshopshopitems_list_size() const {
  return e_personalshopshopitems_list_.size();
}
inline void Sheet_PersonalshopShopitems::clear_e_personalshopshopitems_list() {
  e_personalshopshopitems_list_.Clear();
}
inline const ::proto_ff::E_PersonalshopShopitems& Sheet_PersonalshopShopitems::e_personalshopshopitems_list(int index) const {
  return e_personalshopshopitems_list_.Get(index);
}
inline ::proto_ff::E_PersonalshopShopitems* Sheet_PersonalshopShopitems::mutable_e_personalshopshopitems_list(int index) {
  return e_personalshopshopitems_list_.Mutable(index);
}
inline ::proto_ff::E_PersonalshopShopitems* Sheet_PersonalshopShopitems::add_e_personalshopshopitems_list() {
  return e_personalshopshopitems_list_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::proto_ff::E_PersonalshopShopitems >&
Sheet_PersonalshopShopitems::e_personalshopshopitems_list() const {
  return e_personalshopshopitems_list_;
}
inline ::google::protobuf::RepeatedPtrField< ::proto_ff::E_PersonalshopShopitems >*
Sheet_PersonalshopShopitems::mutable_e_personalshopshopitems_list() {
  return &e_personalshopshopitems_list_;
}

// -------------------------------------------------------------------

// E_PersonalshopShops

// optional int32 m_id = 1;
inline bool E_PersonalshopShops::has_m_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void E_PersonalshopShops::set_has_m_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void E_PersonalshopShops::clear_has_m_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void E_PersonalshopShops::clear_m_id() {
  m_id_ = 0;
  clear_has_m_id();
}
inline ::google::protobuf::int32 E_PersonalshopShops::m_id() const {
  return m_id_;
}
inline void E_PersonalshopShops::set_m_id(::google::protobuf::int32 value) {
  set_has_m_id();
  m_id_ = value;
}

// optional int32 m_keeptime = 2;
inline bool E_PersonalshopShops::has_m_keeptime() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void E_PersonalshopShops::set_has_m_keeptime() {
  _has_bits_[0] |= 0x00000002u;
}
inline void E_PersonalshopShops::clear_has_m_keeptime() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void E_PersonalshopShops::clear_m_keeptime() {
  m_keeptime_ = 0;
  clear_has_m_keeptime();
}
inline ::google::protobuf::int32 E_PersonalshopShops::m_keeptime() const {
  return m_keeptime_;
}
inline void E_PersonalshopShops::set_m_keeptime(::google::protobuf::int32 value) {
  set_has_m_keeptime();
  m_keeptime_ = value;
}

// optional int32 m_freetimes = 3;
inline bool E_PersonalshopShops::has_m_freetimes() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void E_PersonalshopShops::set_has_m_freetimes() {
  _has_bits_[0] |= 0x00000004u;
}
inline void E_PersonalshopShops::clear_has_m_freetimes() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void E_PersonalshopShops::clear_m_freetimes() {
  m_freetimes_ = 0;
  clear_has_m_freetimes();
}
inline ::google::protobuf::int32 E_PersonalshopShops::m_freetimes() const {
  return m_freetimes_;
}
inline void E_PersonalshopShops::set_m_freetimes(::google::protobuf::int32 value) {
  set_has_m_freetimes();
  m_freetimes_ = value;
}

// optional int32 m_refreshmoney = 4;
inline bool E_PersonalshopShops::has_m_refreshmoney() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void E_PersonalshopShops::set_has_m_refreshmoney() {
  _has_bits_[0] |= 0x00000008u;
}
inline void E_PersonalshopShops::clear_has_m_refreshmoney() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void E_PersonalshopShops::clear_m_refreshmoney() {
  m_refreshmoney_ = 0;
  clear_has_m_refreshmoney();
}
inline ::google::protobuf::int32 E_PersonalshopShops::m_refreshmoney() const {
  return m_refreshmoney_;
}
inline void E_PersonalshopShops::set_m_refreshmoney(::google::protobuf::int32 value) {
  set_has_m_refreshmoney();
  m_refreshmoney_ = value;
}

// optional int32 m_refreshprice = 5;
inline bool E_PersonalshopShops::has_m_refreshprice() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void E_PersonalshopShops::set_has_m_refreshprice() {
  _has_bits_[0] |= 0x00000010u;
}
inline void E_PersonalshopShops::clear_has_m_refreshprice() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void E_PersonalshopShops::clear_m_refreshprice() {
  m_refreshprice_ = 0;
  clear_has_m_refreshprice();
}
inline ::google::protobuf::int32 E_PersonalshopShops::m_refreshprice() const {
  return m_refreshprice_;
}
inline void E_PersonalshopShops::set_m_refreshprice(::google::protobuf::int32 value) {
  set_has_m_refreshprice();
  m_refreshprice_ = value;
}

// optional int32 m_salelistcount = 6;
inline bool E_PersonalshopShops::has_m_salelistcount() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void E_PersonalshopShops::set_has_m_salelistcount() {
  _has_bits_[0] |= 0x00000020u;
}
inline void E_PersonalshopShops::clear_has_m_salelistcount() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void E_PersonalshopShops::clear_m_salelistcount() {
  m_salelistcount_ = 0;
  clear_has_m_salelistcount();
}
inline ::google::protobuf::int32 E_PersonalshopShops::m_salelistcount() const {
  return m_salelistcount_;
}
inline void E_PersonalshopShops::set_m_salelistcount(::google::protobuf::int32 value) {
  set_has_m_salelistcount();
  m_salelistcount_ = value;
}

// optional int32 m_addtype = 7;
inline bool E_PersonalshopShops::has_m_addtype() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void E_PersonalshopShops::set_has_m_addtype() {
  _has_bits_[0] |= 0x00000040u;
}
inline void E_PersonalshopShops::clear_has_m_addtype() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void E_PersonalshopShops::clear_m_addtype() {
  m_addtype_ = 0;
  clear_has_m_addtype();
}
inline ::google::protobuf::int32 E_PersonalshopShops::m_addtype() const {
  return m_addtype_;
}
inline void E_PersonalshopShops::set_m_addtype(::google::protobuf::int32 value) {
  set_has_m_addtype();
  m_addtype_ = value;
}

// optional int32 m_addtypevalue = 8;
inline bool E_PersonalshopShops::has_m_addtypevalue() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void E_PersonalshopShops::set_has_m_addtypevalue() {
  _has_bits_[0] |= 0x00000080u;
}
inline void E_PersonalshopShops::clear_has_m_addtypevalue() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void E_PersonalshopShops::clear_m_addtypevalue() {
  m_addtypevalue_ = 0;
  clear_has_m_addtypevalue();
}
inline ::google::protobuf::int32 E_PersonalshopShops::m_addtypevalue() const {
  return m_addtypevalue_;
}
inline void E_PersonalshopShops::set_m_addtypevalue(::google::protobuf::int32 value) {
  set_has_m_addtypevalue();
  m_addtypevalue_ = value;
}

// -------------------------------------------------------------------

// Sheet_PersonalshopShops

// repeated .proto_ff.E_PersonalshopShops E_PersonalshopShops_List = 1;
inline int Sheet_PersonalshopShops::e_personalshopshops_list_size() const {
  return e_personalshopshops_list_.size();
}
inline void Sheet_PersonalshopShops::clear_e_personalshopshops_list() {
  e_personalshopshops_list_.Clear();
}
inline const ::proto_ff::E_PersonalshopShops& Sheet_PersonalshopShops::e_personalshopshops_list(int index) const {
  return e_personalshopshops_list_.Get(index);
}
inline ::proto_ff::E_PersonalshopShops* Sheet_PersonalshopShops::mutable_e_personalshopshops_list(int index) {
  return e_personalshopshops_list_.Mutable(index);
}
inline ::proto_ff::E_PersonalshopShops* Sheet_PersonalshopShops::add_e_personalshopshops_list() {
  return e_personalshopshops_list_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::proto_ff::E_PersonalshopShops >&
Sheet_PersonalshopShops::e_personalshopshops_list() const {
  return e_personalshopshops_list_;
}
inline ::google::protobuf::RepeatedPtrField< ::proto_ff::E_PersonalshopShops >*
Sheet_PersonalshopShops::mutable_e_personalshopshops_list() {
  return &e_personalshopshops_list_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto_ff

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_E_5fPersonalshop_2eproto__INCLUDED
