// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "msg.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace proto_ff {

namespace {

const ::google::protobuf::Descriptor* E_MsgPhpmsg_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  E_MsgPhpmsg_reflection_ = NULL;
const ::google::protobuf::Descriptor* Sheet_MsgPhpmsg_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Sheet_MsgPhpmsg_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_msg_2eproto() {
  protobuf_AddDesc_msg_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "msg.proto");
  GOOGLE_CHECK(file != NULL);
  E_MsgPhpmsg_descriptor_ = file->message_type(0);
  static const int E_MsgPhpmsg_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(E_MsgPhpmsg, m_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(E_MsgPhpmsg, m_content_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(E_MsgPhpmsg, m_note_),
  };
  E_MsgPhpmsg_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      E_MsgPhpmsg_descriptor_,
      E_MsgPhpmsg::default_instance_,
      E_MsgPhpmsg_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(E_MsgPhpmsg, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(E_MsgPhpmsg, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(E_MsgPhpmsg));
  Sheet_MsgPhpmsg_descriptor_ = file->message_type(1);
  static const int Sheet_MsgPhpmsg_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Sheet_MsgPhpmsg, e_msgphpmsg_list_),
  };
  Sheet_MsgPhpmsg_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Sheet_MsgPhpmsg_descriptor_,
      Sheet_MsgPhpmsg::default_instance_,
      Sheet_MsgPhpmsg_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Sheet_MsgPhpmsg, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Sheet_MsgPhpmsg, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Sheet_MsgPhpmsg));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_msg_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    E_MsgPhpmsg_descriptor_, &E_MsgPhpmsg::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Sheet_MsgPhpmsg_descriptor_, &Sheet_MsgPhpmsg::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_msg_2eproto() {
  delete E_MsgPhpmsg::default_instance_;
  delete E_MsgPhpmsg_reflection_;
  delete Sheet_MsgPhpmsg::default_instance_;
  delete Sheet_MsgPhpmsg_reflection_;
}

void protobuf_AddDesc_msg_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::yd_fieldoptions::protobuf_AddDesc_yd_5ffieldoptions_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\tmsg.proto\022\010proto_ff\032\025yd_fieldoptions.p"
    "roto\"q\n\013E_MsgPhpmsg\022\030\n\004m_id\030\001 \001(\005B\n\302\377\024\006\344"
    "\270\213\346\240\207\022(\n\tm_content\030\002 \001(\tB\025\302\377\024\014\346\230\276\347\244\272\344\277\241\346"
    "\201\257\220\301\024\240\001\022\036\n\006m_note\030\003 \001(\tB\016\302\377\024\006\345\244\207\346\263\250\220\301\024<\""
    "I\n\017Sheet_MsgPhpmsg\0226\n\020E_MsgPhpmsg_List\030\001"
    " \003(\0132\025.proto_ff.E_MsgPhpmsgB\005\210\301\024\310\001", 234);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "msg.proto", &protobuf_RegisterTypes);
  E_MsgPhpmsg::default_instance_ = new E_MsgPhpmsg();
  Sheet_MsgPhpmsg::default_instance_ = new Sheet_MsgPhpmsg();
  E_MsgPhpmsg::default_instance_->InitAsDefaultInstance();
  Sheet_MsgPhpmsg::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_msg_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_msg_2eproto {
  StaticDescriptorInitializer_msg_2eproto() {
    protobuf_AddDesc_msg_2eproto();
  }
} static_descriptor_initializer_msg_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int E_MsgPhpmsg::kMIdFieldNumber;
const int E_MsgPhpmsg::kMContentFieldNumber;
const int E_MsgPhpmsg::kMNoteFieldNumber;
#endif  // !_MSC_VER

E_MsgPhpmsg::E_MsgPhpmsg()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void E_MsgPhpmsg::InitAsDefaultInstance() {
}

E_MsgPhpmsg::E_MsgPhpmsg(const E_MsgPhpmsg& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void E_MsgPhpmsg::SharedCtor() {
  _cached_size_ = 0;
  m_id_ = 0;
  m_content_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  m_note_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

E_MsgPhpmsg::~E_MsgPhpmsg() {
  SharedDtor();
}

void E_MsgPhpmsg::SharedDtor() {
  if (m_content_ != &::google::protobuf::internal::kEmptyString) {
    delete m_content_;
  }
  if (m_note_ != &::google::protobuf::internal::kEmptyString) {
    delete m_note_;
  }
  if (this != default_instance_) {
  }
}

void E_MsgPhpmsg::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* E_MsgPhpmsg::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return E_MsgPhpmsg_descriptor_;
}

const E_MsgPhpmsg& E_MsgPhpmsg::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_msg_2eproto();
  return *default_instance_;
}

E_MsgPhpmsg* E_MsgPhpmsg::default_instance_ = NULL;

E_MsgPhpmsg* E_MsgPhpmsg::New() const {
  return new E_MsgPhpmsg;
}

void E_MsgPhpmsg::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    m_id_ = 0;
    if (has_m_content()) {
      if (m_content_ != &::google::protobuf::internal::kEmptyString) {
        m_content_->clear();
      }
    }
    if (has_m_note()) {
      if (m_note_ != &::google::protobuf::internal::kEmptyString) {
        m_note_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool E_MsgPhpmsg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 m_id = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &m_id_)));
          set_has_m_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_m_content;
        break;
      }

      // optional string m_content = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_m_content:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_m_content()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->m_content().data(), this->m_content().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_m_note;
        break;
      }

      // optional string m_note = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_m_note:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_m_note()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->m_note().data(), this->m_note().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void E_MsgPhpmsg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional int32 m_id = 1;
  if (has_m_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->m_id(), output);
  }

  // optional string m_content = 2;
  if (has_m_content()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->m_content().data(), this->m_content().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->m_content(), output);
  }

  // optional string m_note = 3;
  if (has_m_note()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->m_note().data(), this->m_note().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->m_note(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* E_MsgPhpmsg::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional int32 m_id = 1;
  if (has_m_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->m_id(), target);
  }

  // optional string m_content = 2;
  if (has_m_content()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->m_content().data(), this->m_content().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->m_content(), target);
  }

  // optional string m_note = 3;
  if (has_m_note()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->m_note().data(), this->m_note().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->m_note(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int E_MsgPhpmsg::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int32 m_id = 1;
    if (has_m_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->m_id());
    }

    // optional string m_content = 2;
    if (has_m_content()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->m_content());
    }

    // optional string m_note = 3;
    if (has_m_note()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->m_note());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void E_MsgPhpmsg::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const E_MsgPhpmsg* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const E_MsgPhpmsg*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void E_MsgPhpmsg::MergeFrom(const E_MsgPhpmsg& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_m_id()) {
      set_m_id(from.m_id());
    }
    if (from.has_m_content()) {
      set_m_content(from.m_content());
    }
    if (from.has_m_note()) {
      set_m_note(from.m_note());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void E_MsgPhpmsg::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void E_MsgPhpmsg::CopyFrom(const E_MsgPhpmsg& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool E_MsgPhpmsg::IsInitialized() const {

  return true;
}

void E_MsgPhpmsg::Swap(E_MsgPhpmsg* other) {
  if (other != this) {
    std::swap(m_id_, other->m_id_);
    std::swap(m_content_, other->m_content_);
    std::swap(m_note_, other->m_note_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata E_MsgPhpmsg::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = E_MsgPhpmsg_descriptor_;
  metadata.reflection = E_MsgPhpmsg_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int Sheet_MsgPhpmsg::kEMsgPhpmsgListFieldNumber;
#endif  // !_MSC_VER

Sheet_MsgPhpmsg::Sheet_MsgPhpmsg()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void Sheet_MsgPhpmsg::InitAsDefaultInstance() {
}

Sheet_MsgPhpmsg::Sheet_MsgPhpmsg(const Sheet_MsgPhpmsg& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void Sheet_MsgPhpmsg::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Sheet_MsgPhpmsg::~Sheet_MsgPhpmsg() {
  SharedDtor();
}

void Sheet_MsgPhpmsg::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Sheet_MsgPhpmsg::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Sheet_MsgPhpmsg::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Sheet_MsgPhpmsg_descriptor_;
}

const Sheet_MsgPhpmsg& Sheet_MsgPhpmsg::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_msg_2eproto();
  return *default_instance_;
}

Sheet_MsgPhpmsg* Sheet_MsgPhpmsg::default_instance_ = NULL;

Sheet_MsgPhpmsg* Sheet_MsgPhpmsg::New() const {
  return new Sheet_MsgPhpmsg;
}

void Sheet_MsgPhpmsg::Clear() {
  e_msgphpmsg_list_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Sheet_MsgPhpmsg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .proto_ff.E_MsgPhpmsg E_MsgPhpmsg_List = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_E_MsgPhpmsg_List:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_e_msgphpmsg_list()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_E_MsgPhpmsg_List;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void Sheet_MsgPhpmsg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated .proto_ff.E_MsgPhpmsg E_MsgPhpmsg_List = 1;
  for (int i = 0; i < this->e_msgphpmsg_list_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->e_msgphpmsg_list(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* Sheet_MsgPhpmsg::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated .proto_ff.E_MsgPhpmsg E_MsgPhpmsg_List = 1;
  for (int i = 0; i < this->e_msgphpmsg_list_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->e_msgphpmsg_list(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int Sheet_MsgPhpmsg::ByteSize() const {
  int total_size = 0;

  // repeated .proto_ff.E_MsgPhpmsg E_MsgPhpmsg_List = 1;
  total_size += 1 * this->e_msgphpmsg_list_size();
  for (int i = 0; i < this->e_msgphpmsg_list_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->e_msgphpmsg_list(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Sheet_MsgPhpmsg::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Sheet_MsgPhpmsg* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Sheet_MsgPhpmsg*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Sheet_MsgPhpmsg::MergeFrom(const Sheet_MsgPhpmsg& from) {
  GOOGLE_CHECK_NE(&from, this);
  e_msgphpmsg_list_.MergeFrom(from.e_msgphpmsg_list_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Sheet_MsgPhpmsg::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Sheet_MsgPhpmsg::CopyFrom(const Sheet_MsgPhpmsg& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Sheet_MsgPhpmsg::IsInitialized() const {

  return true;
}

void Sheet_MsgPhpmsg::Swap(Sheet_MsgPhpmsg* other) {
  if (other != this) {
    e_msgphpmsg_list_.Swap(&other->e_msgphpmsg_list_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Sheet_MsgPhpmsg::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Sheet_MsgPhpmsg_descriptor_;
  metadata.reflection = Sheet_MsgPhpmsg_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto_ff

// @@protoc_insertion_point(global_scope)
