#define EOT_DESC_STORE_ALL_REGISTER_DEFINE \
REGISTER_DESCSTORE(MsgPhpmsgDesc);\
REGISTER_DESCSTORE(UiEffectDesc);\
REGISTER_DESCSTORE(RoleBornDesc);\
REGISTER_DESCSTORE(RoleMastermaleDesc);\
REGISTER_DESCSTORE(RoleMasterfemaleDesc);\
REGISTER_DESCSTORE(RoleSicklemaleDesc);\
REGISTER_DESCSTORE(RoleSicklefemaleDesc);\
REGISTER_DESCSTORE(RoleSwordmaleDesc);\
REGISTER_DESCSTORE(RoleSwordfemaleDesc);\
REGISTER_DESCSTORE(RoleTaidaomaleDesc);\
REGISTER_DESCSTORE(RoleTaidaofemaleDesc);\
REGISTER_DESCSTORE(RoleExpDesc);\
REGISTER_DESCSTORE(RoleSkilltypeDesc);\
REGISTER_DESCSTORE(RoleAddskillDesc);\
REGISTER_DESCSTORE(RoleWorldexpDesc);\
REGISTER_DESCSTORE(RandomnameManfirstDesc);\
REGISTER_DESCSTORE(RandomnameMansecondDesc);\
REGISTER_DESCSTORE(RandomnameManthirdDesc);\
REGISTER_DESCSTORE(RandomnameWomanfirstDesc);\
REGISTER_DESCSTORE(RandomnameWomansecondDesc);\
REGISTER_DESCSTORE(RandomnameWomanthirdDesc);\
REGISTER_DESCSTORE(SensitivewordSensitive_wordDesc);\
REGISTER_DESCSTORE(SensitivewordRolesensitiveDesc);\
REGISTER_DESCSTORE(MapMapDesc);\
REGISTER_DESCSTORE(MapItemdropDesc);\
REGISTER_DESCSTORE(MapDestroyitemDesc);\
REGISTER_DESCSTORE(MonsterMonsterDesc);\
REGISTER_DESCSTORE(MonsterDisplayDesc);\
REGISTER_DESCSTORE(MonsterValueDesc);\
REGISTER_DESCSTORE(MonsterValueparamDesc);\
REGISTER_DESCSTORE(MonsterDropDesc);\
REGISTER_DESCSTORE(MountFragmentDesc);\
REGISTER_DESCSTORE(MountValueDesc);\
REGISTER_DESCSTORE(MountDisplayDesc);\
REGISTER_DESCSTORE(MountUnlockDesc);\
REGISTER_DESCSTORE(MountChangeDesc);\
REGISTER_DESCSTORE(MountAdvanceDesc);\
REGISTER_DESCSTORE(MountHuakunDesc);\
REGISTER_DESCSTORE(MountHuakun_advancevalueDesc);\
REGISTER_DESCSTORE(MountBloodDesc);\
REGISTER_DESCSTORE(MountBaby_eggDesc);\
REGISTER_DESCSTORE(AreaAreaDesc);\
REGISTER_DESCSTORE(SkillBuffDesc);\
REGISTER_DESCSTORE(SkillSkillDesc);\
REGISTER_DESCSTORE(SkillBuffupDesc);\
REGISTER_DESCSTORE(SkillSkillupDesc);\
REGISTER_DESCSTORE(SkillSkillawakeDesc);\
REGISTER_DESCSTORE(SkillSkilladvanceDesc);\
REGISTER_DESCSTORE(ItemItemDesc);\
REGISTER_DESCSTORE(EquipEquipDesc);\
REGISTER_DESCSTORE(EquipStrongDesc);\
REGISTER_DESCSTORE(EquipStrongexpDesc);\
REGISTER_DESCSTORE(EquipStrongtotalDesc);\
REGISTER_DESCSTORE(EquipGemDesc);\
REGISTER_DESCSTORE(EquipGemlvDesc);\
REGISTER_DESCSTORE(EquipStoveattDesc);\
REGISTER_DESCSTORE(EquipStoveexpDesc);\
REGISTER_DESCSTORE(EquipGradeDesc);\
REGISTER_DESCSTORE(EquipClearDesc);\
REGISTER_DESCSTORE(EquipSuitDesc);\
REGISTER_DESCSTORE(EquipBreakDesc);\
REGISTER_DESCSTORE(ConstantConstantDesc);\
REGISTER_DESCSTORE(AttributeAttributeDesc);\
REGISTER_DESCSTORE(AttributeSuppressDesc);\
REGISTER_DESCSTORE(AttributePowersupDesc);\
REGISTER_DESCSTORE(FashionFashionDesc);\
REGISTER_DESCSTORE(DecorateDecorateDesc);\
REGISTER_DESCSTORE(FootprintFootprintDesc);\
REGISTER_DESCSTORE(HaloHaloDesc);\
REGISTER_DESCSTORE(HeadportraitHeadDesc);\
REGISTER_DESCSTORE(MeditationMeditationDesc);\
REGISTER_DESCSTORE(FunctionunlockFunctionunlockDesc);\
REGISTER_DESCSTORE(FunctionunlockPreviewDesc);\
REGISTER_DESCSTORE(GmcommandGmcommandDesc);\
REGISTER_DESCSTORE(LinkLinkDesc);\
REGISTER_DESCSTORE(MallMallDesc);\
REGISTER_DESCSTORE(MallMalltypeDesc);\
REGISTER_DESCSTORE(MallMalltype_tabDesc);\
REGISTER_DESCSTORE(ChatChatDesc);\
REGISTER_DESCSTORE(ChatSpecialchatDesc);\
REGISTER_DESCSTORE(PathPathDesc);\
REGISTER_DESCSTORE(IntimacyIntimacyDesc);\
REGISTER_DESCSTORE(IntimacyGiftDesc);\
REGISTER_DESCSTORE(AiAiDesc);\
REGISTER_DESCSTORE(BossRareitemDesc);\
REGISTER_DESCSTORE(BossBossDesc);\
REGISTER_DESCSTORE(BossBosstypeDesc);\
REGISTER_DESCSTORE(BossLayerDesc);\
REGISTER_DESCSTORE(PointPointDesc);\
REGISTER_DESCSTORE(FacadeDisplayDesc);\
REGISTER_DESCSTORE(FacadeValueDesc);\
REGISTER_DESCSTORE(FacadeTypeDesc);\
REGISTER_DESCSTORE(FacadeFragmentDesc);\
REGISTER_DESCSTORE(FacadeChangeDesc);\
REGISTER_DESCSTORE(FacadeStarupDesc);\
REGISTER_DESCSTORE(FacadeSoulDesc);\
REGISTER_DESCSTORE(FacadeSoulactiveDesc);\
REGISTER_DESCSTORE(FacadeSoullvDesc);\
REGISTER_DESCSTORE(FacadeSoulachievementDesc);\
REGISTER_DESCSTORE(DupBplevelDesc);\
REGISTER_DESCSTORE(DupDupDesc);\
REGISTER_DESCSTORE(DupTowerrewardDesc);\
REGISTER_DESCSTORE(DupGroupDesc);\
REGISTER_DESCSTORE(DupSweepmonsternumDesc);\
REGISTER_DESCSTORE(OfflineOfflineDesc);\
REGISTER_DESCSTORE(OfflineItemlistDesc);\
REGISTER_DESCSTORE(GodrelicsGodrelicsDesc);\
REGISTER_DESCSTORE(GodrelicsConditionDesc);\
REGISTER_DESCSTORE(ConditionConditionDesc);\
REGISTER_DESCSTORE(PeractivityPeractivityDesc);\
REGISTER_DESCSTORE(PeractivityWeekDesc);\
REGISTER_DESCSTORE(DailyDailyDesc);\
REGISTER_DESCSTORE(DailyRewardDesc);\
REGISTER_DESCSTORE(DailyCultivateDesc);\
REGISTER_DESCSTORE(BackBackDesc);\
REGISTER_DESCSTORE(TeamTeamDesc);\
REGISTER_DESCSTORE(BoxBoxDesc);\
REGISTER_DESCSTORE(BoxBoxdataDesc);\
REGISTER_DESCSTORE(TaskTaskDesc);\
REGISTER_DESCSTORE(TaskdynamicTaskdynamicDesc);\
REGISTER_DESCSTORE(TaskdynamicTaskcomcondDesc);\
REGISTER_DESCSTORE(TaskdynamicTasktextDesc);\
REGISTER_DESCSTORE(TaskrewardTaskrewardDesc);\
REGISTER_DESCSTORE(TaskrewardTasktypeDesc);\
REGISTER_DESCSTORE(TasktrackerTasktrackerDesc);\
REGISTER_DESCSTORE(FlashFlashDesc);\
REGISTER_DESCSTORE(FlashItemflashDesc);\
REGISTER_DESCSTORE(ButtonButtonDesc);\
REGISTER_DESCSTORE(VipVipDesc);\
REGISTER_DESCSTORE(VipPrivilegeDesc);\
REGISTER_DESCSTORE(ArenaRobotDesc);\
REGISTER_DESCSTORE(ArenaRobotfacadeDesc);\
REGISTER_DESCSTORE(ArenaArenawardDesc);\
REGISTER_DESCSTORE(ArenaRankawardDesc);\
REGISTER_DESCSTORE(ArenaFirstrankDesc);\
REGISTER_DESCSTORE(ArenaBuychallengeDesc);\
REGISTER_DESCSTORE(PetDisplayDesc);\
REGISTER_DESCSTORE(PetAttributetpyeDesc);\
REGISTER_DESCSTORE(PetLvexpDesc);\
REGISTER_DESCSTORE(PetAdvancelvDesc);\
REGISTER_DESCSTORE(PetStarupDesc);\
REGISTER_DESCSTORE(PetEggDesc);\
REGISTER_DESCSTORE(PetDecomposeDesc);\
REGISTER_DESCSTORE(PetFettersDesc);\
REGISTER_DESCSTORE(AvatarFragmentDesc);\
REGISTER_DESCSTORE(AvatarValueDesc);\
REGISTER_DESCSTORE(AvatarDisplayDesc);\
REGISTER_DESCSTORE(AvatarChangeDesc);\
REGISTER_DESCSTORE(AvatarChangetabDesc);\
REGISTER_DESCSTORE(AvatarBattleslotDesc);\
REGISTER_DESCSTORE(AvatarAdvanceDesc);\
REGISTER_DESCSTORE(AvatarSkillDesc);\
REGISTER_DESCSTORE(AvatarEquipsuitDesc);\
REGISTER_DESCSTORE(AssistBoxDesc);\
REGISTER_DESCSTORE(AssistThankDesc);\
REGISTER_DESCSTORE(AssistConstDesc);\
REGISTER_DESCSTORE(MoneyrewardMoneyrewardDesc);\
REGISTER_DESCSTORE(EscortEscortDesc);\
REGISTER_DESCSTORE(EscortChanceDesc);\
REGISTER_DESCSTORE(EscortRewardDesc);\
REGISTER_DESCSTORE(EscortConstDesc);\
REGISTER_DESCSTORE(GuildConstantDesc);\
REGISTER_DESCSTORE(GuildLevelDesc);\
REGISTER_DESCSTORE(GuildPositionDesc);\
REGISTER_DESCSTORE(CollectCollectDesc);\
REGISTER_DESCSTORE(CollectAttributetpyeDesc);\
REGISTER_DESCSTORE(TitleTypeDesc);\
REGISTER_DESCSTORE(TitleTitleDesc);\
