#define EOT_DESC_STORE_ALL_REGISTER_DEFINE \
REGISTER_DESCSTORE(MsgPhpmsgDesc);\
REGISTER_DESCSTORE_EX(MsgDescEx);\
REGISTER_DESCSTORE(UiEffectDesc);\
REGISTER_DESCSTORE_EX(UiDescEx);\
REGISTER_DESCSTORE(RoleBornDesc);\
REGISTER_DESCSTORE(RoleMastermaleDesc);\
REGISTER_DESCSTORE(RoleMasterfemaleDesc);\
REGISTER_DESCSTORE(RoleSicklemaleDesc);\
REGISTER_DESCSTORE(RoleSicklefemaleDesc);\
REGISTER_DESCSTORE(RoleSwordmaleDesc);\
REGISTER_DESCSTORE(RoleSwordfemaleDesc);\
REGISTER_DESCSTORE(RoleTaidaomaleDesc);\
REGISTER_DESCSTORE(RoleTaidaofemaleDesc);\
REGISTER_DESCSTORE(RoleExpDesc);\
REGISTER_DESCSTORE(RoleSkilltypeDesc);\
REGISTER_DESCSTORE(RoleAddskillDesc);\
REGISTER_DESCSTORE(RoleWorldexpDesc);\
REGISTER_DESCSTORE(RoleChangecareerDesc);\
REGISTER_DESCSTORE(RoleCareerpreposeDesc);\
REGISTER_DESCSTORE_EX(RoleDescEx);\
REGISTER_DESCSTORE(RandomnameManfirstDesc);\
REGISTER_DESCSTORE(RandomnameMansecondDesc);\
REGISTER_DESCSTORE(RandomnameManthirdDesc);\
REGISTER_DESCSTORE(RandomnameWomanfirstDesc);\
REGISTER_DESCSTORE(RandomnameWomansecondDesc);\
REGISTER_DESCSTORE(RandomnameWomanthirdDesc);\
REGISTER_DESCSTORE_EX(RandomnameDescEx);\
REGISTER_DESCSTORE(SensitivewordWord1Desc);\
REGISTER_DESCSTORE(SensitivewordWord2Desc);\
REGISTER_DESCSTORE(SensitivewordWord3Desc);\
REGISTER_DESCSTORE_EX(SensitivewordDescEx);\
REGISTER_DESCSTORE(MapMapDesc);\
REGISTER_DESCSTORE(MapItemdropDesc);\
REGISTER_DESCSTORE(MapDestroyitemDesc);\
REGISTER_DESCSTORE(MapButtonDesc);\
REGISTER_DESCSTORE(MapInspireDesc);\
REGISTER_DESCSTORE_EX(MapDescEx);\
REGISTER_DESCSTORE(MonsterMonsterDesc);\
REGISTER_DESCSTORE(MonsterDisplayDesc);\
REGISTER_DESCSTORE(MonsterValueDesc);\
REGISTER_DESCSTORE(MonsterValueparamDesc);\
REGISTER_DESCSTORE(MonsterDropDesc);\
REGISTER_DESCSTORE(MonsterCollectDesc);\
REGISTER_DESCSTORE_EX(MonsterDescEx);\
REGISTER_DESCSTORE(MountFragmentDesc);\
REGISTER_DESCSTORE(MountValueDesc);\
REGISTER_DESCSTORE(MountDisplayDesc);\
REGISTER_DESCSTORE(MountUnlockDesc);\
REGISTER_DESCSTORE(MountChangeDesc);\
REGISTER_DESCSTORE(MountAdvanceDesc);\
REGISTER_DESCSTORE(MountBaby_eggDesc);\
REGISTER_DESCSTORE(MountHuakunDesc);\
REGISTER_DESCSTORE(MountHuakun_valueDesc);\
REGISTER_DESCSTORE(MountHuakun_advancevalueDesc);\
REGISTER_DESCSTORE(MountHuakun_changeDesc);\
REGISTER_DESCSTORE(MountHuakun_advanceDesc);\
REGISTER_DESCSTORE(MountBloodDesc);\
REGISTER_DESCSTORE(MountHuakun_equipDesc);\
REGISTER_DESCSTORE(MountEquip_valueDesc);\
REGISTER_DESCSTORE(MountEquipsuitDesc);\
REGISTER_DESCSTORE(MountEquiptopDesc);\
REGISTER_DESCSTORE(MountEquiptopvalueDesc);\
REGISTER_DESCSTORE(MountEquippartDesc);\
REGISTER_DESCSTORE(MountEmpowermenttour_debrisDesc);\
REGISTER_DESCSTORE(MountEmpowermentDesc);\
REGISTER_DESCSTORE(MountEmpowerment_positionDesc);\
REGISTER_DESCSTORE(MountEmpowerment_slotDesc);\
REGISTER_DESCSTORE(MountEmpowerment_eventDesc);\
REGISTER_DESCSTORE_EX(MountDescEx);\
REGISTER_DESCSTORE(AreaAreaDesc);\
REGISTER_DESCSTORE_EX(AreaDescEx);\
REGISTER_DESCSTORE(SkillBuffDesc);\
REGISTER_DESCSTORE(SkillBuffupDesc);\
REGISTER_DESCSTORE(SkillSkillDesc);\
REGISTER_DESCSTORE(SkillSkilladvanceDesc);\
REGISTER_DESCSTORE(SkillSkillupDesc);\
REGISTER_DESCSTORE(SkillSkillawakeDesc);\
REGISTER_DESCSTORE(SkillSkillgroupDesc);\
REGISTER_DESCSTORE(SkillAttgroupDesc);\
REGISTER_DESCSTORE_EX(SkillDescEx);\
REGISTER_DESCSTORE(ItemItemDesc);\
REGISTER_DESCSTORE_EX(ItemDescEx);\
REGISTER_DESCSTORE(EquipEquipDesc);\
REGISTER_DESCSTORE(EquipAttributeDesc);\
REGISTER_DESCSTORE(EquipSpecattDesc);\
REGISTER_DESCSTORE(EquipStrongDesc);\
REGISTER_DESCSTORE(EquipStrongexpDesc);\
REGISTER_DESCSTORE(EquipBeaststrongDesc);\
REGISTER_DESCSTORE(EquipStrongtotalDesc);\
REGISTER_DESCSTORE(EquipGemDesc);\
REGISTER_DESCSTORE(EquipGemlvDesc);\
REGISTER_DESCSTORE(EquipStoveattDesc);\
REGISTER_DESCSTORE(EquipStoveexpDesc);\
REGISTER_DESCSTORE(EquipGradeDesc);\
REGISTER_DESCSTORE(EquipClearDesc);\
REGISTER_DESCSTORE(EquipSuitDesc);\
REGISTER_DESCSTORE(EquipBreakDesc);\
REGISTER_DESCSTORE_EX(EquipDescEx);\
REGISTER_DESCSTORE(ConstantConstantDesc);\
REGISTER_DESCSTORE_EX(ConstantDescEx);\
REGISTER_DESCSTORE(AttributeAttributeDesc);\
REGISTER_DESCSTORE(AttributeSuppressDesc);\
REGISTER_DESCSTORE(AttributePowersupDesc);\
REGISTER_DESCSTORE_EX(AttributeDescEx);\
REGISTER_DESCSTORE(FashionFashionDesc);\
REGISTER_DESCSTORE_EX(FashionDescEx);\
REGISTER_DESCSTORE(DecorateDecorateDesc);\
REGISTER_DESCSTORE_EX(DecorateDescEx);\
REGISTER_DESCSTORE(FootprintFootprintDesc);\
REGISTER_DESCSTORE_EX(FootprintDescEx);\
REGISTER_DESCSTORE(HaloHaloDesc);\
REGISTER_DESCSTORE_EX(HaloDescEx);\
REGISTER_DESCSTORE(HeadportraitHeadDesc);\
REGISTER_DESCSTORE_EX(HeadportraitDescEx);\
REGISTER_DESCSTORE(MeditationMeditationDesc);\
REGISTER_DESCSTORE_EX(MeditationDescEx);\
REGISTER_DESCSTORE(FunctionunlockFunctionunlockDesc);\
REGISTER_DESCSTORE(FunctionunlockPreviewDesc);\
REGISTER_DESCSTORE_EX(FunctionunlockDescEx);\
REGISTER_DESCSTORE(GmcommandGmcommandDesc);\
REGISTER_DESCSTORE_EX(GmcommandDescEx);\
REGISTER_DESCSTORE_EX(AppearanceDescEx);\
REGISTER_DESCSTORE(LinkLinkDesc);\
REGISTER_DESCSTORE(LinkImagelinkDesc);\
REGISTER_DESCSTORE_EX(LinkDescEx);\
REGISTER_DESCSTORE_EX(MailDescEx);\
REGISTER_DESCSTORE(MallMallDesc);\
REGISTER_DESCSTORE(MallMalltype_tabDesc);\
REGISTER_DESCSTORE(MallMalltypeDesc);\
REGISTER_DESCSTORE(MallHolybeastDesc);\
REGISTER_DESCSTORE_EX(MallDescEx);\
REGISTER_DESCSTORE(ChatChatDesc);\
REGISTER_DESCSTORE(ChatSpecialchatDesc);\
REGISTER_DESCSTORE_EX(ChatDescEx);\
REGISTER_DESCSTORE(PathPathDesc);\
REGISTER_DESCSTORE_EX(PathDescEx);\
REGISTER_DESCSTORE(IntimacyIntimacyDesc);\
REGISTER_DESCSTORE(IntimacyGiftDesc);\
REGISTER_DESCSTORE_EX(IntimacyDescEx);\
REGISTER_DESCSTORE(AiAiDesc);\
REGISTER_DESCSTORE_EX(AiDescEx);\
REGISTER_DESCSTORE(BossRareitemDesc);\
REGISTER_DESCSTORE(BossBosstypeDesc);\
REGISTER_DESCSTORE(BossBossDesc);\
REGISTER_DESCSTORE(BossLayerDesc);\
REGISTER_DESCSTORE_EX(BossDescEx);\
REGISTER_DESCSTORE(PointPointDesc);\
REGISTER_DESCSTORE_EX(PointDescEx);\
REGISTER_DESCSTORE(FacadeDisplayDesc);\
REGISTER_DESCSTORE(FacadeValueDesc);\
REGISTER_DESCSTORE(FacadeTypeDesc);\
REGISTER_DESCSTORE(FacadeFragmentDesc);\
REGISTER_DESCSTORE(FacadeChangeDesc);\
REGISTER_DESCSTORE(FacadeStarupDesc);\
REGISTER_DESCSTORE(FacadeSoulDesc);\
REGISTER_DESCSTORE(FacadeSoulactiveDesc);\
REGISTER_DESCSTORE(FacadeSoullvDesc);\
REGISTER_DESCSTORE(FacadeSoulachievementDesc);\
REGISTER_DESCSTORE_EX(FacadeDescEx);\
REGISTER_DESCSTORE(DupDupDesc);\
REGISTER_DESCSTORE(DupBplevelDesc);\
REGISTER_DESCSTORE(DupTtowerwaveDesc);\
REGISTER_DESCSTORE(DupTowerrewardDesc);\
REGISTER_DESCSTORE(DupGroupDesc);\
REGISTER_DESCSTORE(DupSweepmonsternumDesc);\
REGISTER_DESCSTORE(DupWorldlvrewardDesc);\
REGISTER_DESCSTORE(DupPlanesDesc);\
REGISTER_DESCSTORE(DupYt_dupDesc);\
REGISTER_DESCSTORE_EX(DupDescEx);\
REGISTER_DESCSTORE(OfflineOfflineDesc);\
REGISTER_DESCSTORE(OfflineItemlistDesc);\
REGISTER_DESCSTORE_EX(OfflineDescEx);\
REGISTER_DESCSTORE(GodrelicsGodrelicsDesc);\
REGISTER_DESCSTORE(GodrelicsConditionDesc);\
REGISTER_DESCSTORE_EX(GodrelicsDescEx);\
REGISTER_DESCSTORE(ConditionConditionDesc);\
REGISTER_DESCSTORE_EX(ConditionDescEx);\
REGISTER_DESCSTORE_EX(AudioDescEx);\
REGISTER_DESCSTORE(PeractivityPeractivityDesc);\
REGISTER_DESCSTORE(PeractivityWeekDesc);\
REGISTER_DESCSTORE_EX(PeractivityDescEx);\
REGISTER_DESCSTORE(DailyDailyDesc);\
REGISTER_DESCSTORE(DailyRewardDesc);\
REGISTER_DESCSTORE(DailyCultivateDesc);\
REGISTER_DESCSTORE(DailySportsDesc);\
REGISTER_DESCSTORE(DailyHelperDesc);\
REGISTER_DESCSTORE_EX(DailyDescEx);\
REGISTER_DESCSTORE(BackBackDesc);\
REGISTER_DESCSTORE_EX(BackDescEx);\
REGISTER_DESCSTORE_EX(SetDescEx);\
REGISTER_DESCSTORE(TeamTeamDesc);\
REGISTER_DESCSTORE_EX(TeamDescEx);\
REGISTER_DESCSTORE(BoxBoxDesc);\
REGISTER_DESCSTORE(BoxBoxdataDesc);\
REGISTER_DESCSTORE_EX(BoxDescEx);\
REGISTER_DESCSTORE(TaskTaskDesc);\
REGISTER_DESCSTORE_EX(TaskDescEx);\
REGISTER_DESCSTORE(TaskdynamicTaskdynamicDesc);\
REGISTER_DESCSTORE(TaskdynamicTaskcomcondDesc);\
REGISTER_DESCSTORE(TaskdynamicTasktextDesc);\
REGISTER_DESCSTORE_EX(TaskdynamicDescEx);\
REGISTER_DESCSTORE(TaskrewardTaskrewardDesc);\
REGISTER_DESCSTORE(TaskrewardTasktypeDesc);\
REGISTER_DESCSTORE_EX(TaskrewardDescEx);\
REGISTER_DESCSTORE(TasktrackerTasktrackerDesc);\
REGISTER_DESCSTORE_EX(TasktrackerDescEx);\
REGISTER_DESCSTORE(FlashFlashDesc);\
REGISTER_DESCSTORE(FlashItemflashDesc);\
REGISTER_DESCSTORE_EX(FlashDescEx);\
REGISTER_DESCSTORE(ButtonButtonDesc);\
REGISTER_DESCSTORE_EX(ButtonDescEx);\
REGISTER_DESCSTORE(VipVipDesc);\
REGISTER_DESCSTORE(VipPrivilegeDesc);\
REGISTER_DESCSTORE(VipChatDesc);\
REGISTER_DESCSTORE(VipCosntantDesc);\
REGISTER_DESCSTORE(VipExplimitDesc);\
REGISTER_DESCSTORE_EX(VipDescEx);\
REGISTER_DESCSTORE(ArenaRobotDesc);\
REGISTER_DESCSTORE(ArenaRobotfacadeDesc);\
REGISTER_DESCSTORE(ArenaArenawardDesc);\
REGISTER_DESCSTORE(ArenaRankawardDesc);\
REGISTER_DESCSTORE(ArenaFirstrankDesc);\
REGISTER_DESCSTORE(ArenaBuychallengeDesc);\
REGISTER_DESCSTORE_EX(ArenaDescEx);\
REGISTER_DESCSTORE(PetDisplayDesc);\
REGISTER_DESCSTORE(PetAttributetpyeDesc);\
REGISTER_DESCSTORE(PetLvexpDesc);\
REGISTER_DESCSTORE(PetAdvancelvDesc);\
REGISTER_DESCSTORE(PetStarupDesc);\
REGISTER_DESCSTORE(PetEggDesc);\
REGISTER_DESCSTORE(PetDecomposeDesc);\
REGISTER_DESCSTORE(PetFettersDesc);\
REGISTER_DESCSTORE(PetPetequipDesc);\
REGISTER_DESCSTORE(PetEquipvalueDesc);\
REGISTER_DESCSTORE(PetStarvalueDesc);\
REGISTER_DESCSTORE(PetWraithsDesc);\
REGISTER_DESCSTORE(PetWraithslvDesc);\
REGISTER_DESCSTORE(PetSmeltDesc);\
REGISTER_DESCSTORE(PetRefineconversionDesc);\
REGISTER_DESCSTORE(PetStoveDesc);\
REGISTER_DESCSTORE(PetSuitDesc);\
REGISTER_DESCSTORE(PetConstDesc);\
REGISTER_DESCSTORE(PetTopDesc);\
REGISTER_DESCSTORE(PetTopitemDesc);\
REGISTER_DESCSTORE(PetPrivilegeDesc);\
REGISTER_DESCSTORE_EX(PetDescEx);\
REGISTER_DESCSTORE(AvatarFragmentDesc);\
REGISTER_DESCSTORE(AvatarValueDesc);\
REGISTER_DESCSTORE(AvatarDisplayDesc);\
REGISTER_DESCSTORE(AvatarChangeDesc);\
REGISTER_DESCSTORE(AvatarChangetabDesc);\
REGISTER_DESCSTORE(AvatarBattleslotDesc);\
REGISTER_DESCSTORE(AvatarAdvanceDesc);\
REGISTER_DESCSTORE(AvatarSkillDesc);\
REGISTER_DESCSTORE(AvatarEquipsuitDesc);\
REGISTER_DESCSTORE(AvatarMythDesc);\
REGISTER_DESCSTORE(AvatarMythwayDesc);\
REGISTER_DESCSTORE(AvatarMythcoreDesc);\
REGISTER_DESCSTORE(AvatarMythequipDesc);\
REGISTER_DESCSTORE(AvatarArtifactDesc);\
REGISTER_DESCSTORE(AvatarArtifact_facadeDesc);\
REGISTER_DESCSTORE(AvatarArtifact_starDesc);\
REGISTER_DESCSTORE(AvatarArtifact_strengthenDesc);\
REGISTER_DESCSTORE(AvatarArtifact_enchantDesc);\
REGISTER_DESCSTORE(AvatarArtifact_decomposeDesc);\
REGISTER_DESCSTORE_EX(AvatarDescEx);\
REGISTER_DESCSTORE(AssistBoxDesc);\
REGISTER_DESCSTORE(AssistThankDesc);\
REGISTER_DESCSTORE(AssistConstDesc);\
REGISTER_DESCSTORE_EX(AssistDescEx);\
REGISTER_DESCSTORE(MoneyrewardMoneyrewardDesc);\
REGISTER_DESCSTORE_EX(MoneyrewardDescEx);\
REGISTER_DESCSTORE(EscortEscortDesc);\
REGISTER_DESCSTORE(EscortChanceDesc);\
REGISTER_DESCSTORE(EscortRewardDesc);\
REGISTER_DESCSTORE(EscortConstDesc);\
REGISTER_DESCSTORE_EX(EscortDescEx);\
REGISTER_DESCSTORE(GuildConstantDesc);\
REGISTER_DESCSTORE(GuildLevelDesc);\
REGISTER_DESCSTORE(GuildPositionDesc);\
REGISTER_DESCSTORE(GuildSalaryDesc);\
REGISTER_DESCSTORE(GuildDonateDesc);\
REGISTER_DESCSTORE(GuildPacketDesc);\
REGISTER_DESCSTORE(GuildPrestigetaskDesc);\
REGISTER_DESCSTORE(GuildLvrewardDesc);\
REGISTER_DESCSTORE(GuildCollegeDesc);\
REGISTER_DESCSTORE(GuildAnswerDesc);\
REGISTER_DESCSTORE(GuildRank_rewardDesc);\
REGISTER_DESCSTORE(GuildShouhskillDesc);\
REGISTER_DESCSTORE(GuildGwrewardDesc);\
REGISTER_DESCSTORE(GuildGwwinstreakDesc);\
REGISTER_DESCSTORE(GuildTtowerDesc);\
REGISTER_DESCSTORE(GuildTtowerdevelopDesc);\
REGISTER_DESCSTORE(GuildTtowerdevelop_dataDesc);\
REGISTER_DESCSTORE_EX(GuildDescEx);\
REGISTER_DESCSTORE(CollectCollectDesc);\
REGISTER_DESCSTORE(CollectAttributetpyeDesc);\
REGISTER_DESCSTORE_EX(CollectDescEx);\
REGISTER_DESCSTORE(TitleTypeDesc);\
REGISTER_DESCSTORE(TitleTitleDesc);\
REGISTER_DESCSTORE_EX(TitleDescEx);\
REGISTER_DESCSTORE(GodevilPreposetaskDesc);\
REGISTER_DESCSTORE(GodevilGodevillvDesc);\
REGISTER_DESCSTORE(GodevilGodevilprivilegeDesc);\
REGISTER_DESCSTORE(GodevilStrongDesc);\
REGISTER_DESCSTORE(GodevilStrongexpDesc);\
REGISTER_DESCSTORE(GodevilAdvancelvDesc);\
REGISTER_DESCSTORE(GodevilAdvanceexpDesc);\
REGISTER_DESCSTORE(GodevilQualitylvDesc);\
REGISTER_DESCSTORE(GodevilPositionunlockDesc);\
REGISTER_DESCSTORE(GodevilBlacksmithDesc);\
REGISTER_DESCSTORE(GodevilGodevilskillDesc);\
REGISTER_DESCSTORE(GodevilPrefixnameDesc);\
REGISTER_DESCSTORE_EX(GodevilDescEx);\
REGISTER_DESCSTORE(OccupationOccupationDesc);\
REGISTER_DESCSTORE(OccupationStageDesc);\
REGISTER_DESCSTORE(OccupationAttributeDesc);\
REGISTER_DESCSTORE(OccupationSoulDesc);\
REGISTER_DESCSTORE_EX(OccupationDescEx);\
REGISTER_DESCSTORE(GodvalleyBattleDesc);\
REGISTER_DESCSTORE(GodvalleyRewardsDesc);\
REGISTER_DESCSTORE(GodvalleyAttributeDesc);\
REGISTER_DESCSTORE_EX(GodvalleyDescEx);\
REGISTER_DESCSTORE(RechargeRechargeDesc);\
REGISTER_DESCSTORE(RechargeOneclickbuyDesc);\
REGISTER_DESCSTORE_EX(RechargeDescEx);\
REGISTER_DESCSTORE(ShenequipEquipDesc);\
REGISTER_DESCSTORE(ShenequipAttDesc);\
REGISTER_DESCSTORE(ShenequipLvupDesc);\
REGISTER_DESCSTORE(ShenequipClearDesc);\
REGISTER_DESCSTORE(ShenequipAwakenDesc);\
REGISTER_DESCSTORE(ShenequipStarupDesc);\
REGISTER_DESCSTORE(ShenequipPreposeDesc);\
REGISTER_DESCSTORE(ShenequipDominanceDesc);\
REGISTER_DESCSTORE(ShenequipAdvancedDesc);\
REGISTER_DESCSTORE(ShenequipTalentDesc);\
REGISTER_DESCSTORE(ShenequipTalenttypeDesc);\
REGISTER_DESCSTORE(ShenequipPreviewDesc);\
REGISTER_DESCSTORE_EX(ShenequipDescEx);\
REGISTER_DESCSTORE(AchievementAchievementDesc);\
REGISTER_DESCSTORE(AchievementTotalachievementsDesc);\
REGISTER_DESCSTORE_EX(AchievementDescEx);\
REGISTER_DESCSTORE(AncientgodAncientgodDesc);\
REGISTER_DESCSTORE(AncientgodLvupDesc);\
REGISTER_DESCSTORE(AncientgodEquipvalueDesc);\
REGISTER_DESCSTORE(AncientgodBlessDesc);\
REGISTER_DESCSTORE(AncientgodAdvanceDesc);\
REGISTER_DESCSTORE(AncientgodAttDesc);\
REGISTER_DESCSTORE(AncientgodStarcollectDesc);\
REGISTER_DESCSTORE_EX(AncientgodDescEx);\
REGISTER_DESCSTORE(XiuzhenStagesDesc);\
REGISTER_DESCSTORE(XiuzhenGb_areasDesc);\
REGISTER_DESCSTORE(XiuzhenGb_area_eventsDesc);\
REGISTER_DESCSTORE(XiuzhenGb_lvlupDesc);\
REGISTER_DESCSTORE(XiuzhenEvolveDesc);\
REGISTER_DESCSTORE(XiuzhenLgtypesDesc);\
REGISTER_DESCSTORE(XiuzhenLglvlupDesc);\
REGISTER_DESCSTORE(XiuzhenLgpotionsDesc);\
REGISTER_DESCSTORE(XiuzhenGftypesDesc);\
REGISTER_DESCSTORE(XiuzhenGflvlupDesc);\
REGISTER_DESCSTORE(XiuzhenGfstageupDesc);\
REGISTER_DESCSTORE(XiuzhenJmtypesDesc);\
REGISTER_DESCSTORE(XiuzhenJmlvlupDesc);\
REGISTER_DESCSTORE(XiuzhenJmstageupDesc);\
REGISTER_DESCSTORE(XiuzhenJmmergeupDesc);\
REGISTER_DESCSTORE(XiuzhenPrivilegeDesc);\
REGISTER_DESCSTORE_EX(XiuzhenDescEx);\
REGISTER_DESCSTORE(EncyclopediaHandbookDesc);\
REGISTER_DESCSTORE(EncyclopediaHandbookfateDesc);\
REGISTER_DESCSTORE(EncyclopediaHandbookresolveDesc);\
REGISTER_DESCSTORE(EncyclopediaHandbooklv_attrDesc);\
REGISTER_DESCSTORE(EncyclopediaHandbookstar_attrDesc);\
REGISTER_DESCSTORE(EncyclopediaBeastDesc);\
REGISTER_DESCSTORE(EncyclopediaEquipexpvalueDesc);\
REGISTER_DESCSTORE(EncyclopediaBeastexpandDesc);\
REGISTER_DESCSTORE(EncyclopediaBeastprivilegeDesc);\
REGISTER_DESCSTORE(EncyclopediaBeastexpDesc);\
REGISTER_DESCSTORE(EncyclopediaEmployDesc);\
REGISTER_DESCSTORE(EncyclopediaTableDesc);\
REGISTER_DESCSTORE_EX(EncyclopediaDescEx);\
REGISTER_DESCSTORE(TalentTalentDesc);\
REGISTER_DESCSTORE(TalentTalenttypeDesc);\
REGISTER_DESCSTORE_EX(TalentDescEx);\
REGISTER_DESCSTORE(MarryMarriageDesc);\
REGISTER_DESCSTORE(MarryBanquetDesc);\
REGISTER_DESCSTORE(MarryLocklvDesc);\
REGISTER_DESCSTORE(MarryLockskillDesc);\
REGISTER_DESCSTORE(MarryChildDesc);\
REGISTER_DESCSTORE(MarryChildvalueDesc);\
REGISTER_DESCSTORE(MarryChildexpDesc);\
REGISTER_DESCSTORE(MarryExpressDesc);\
REGISTER_DESCSTORE(MarryExpresslanguageDesc);\
REGISTER_DESCSTORE(MarryExpressshopDesc);\
REGISTER_DESCSTORE(MarryConstantDesc);\
REGISTER_DESCSTORE(MarryCommonDesc);\
REGISTER_DESCSTORE(MarryWeddingDesc);\
REGISTER_DESCSTORE(MarryExpDesc);\
REGISTER_DESCSTORE_EX(MarryDescEx);\
REGISTER_DESCSTORE(RankingRankingDesc);\
REGISTER_DESCSTORE(RankingDateDesc);\
REGISTER_DESCSTORE(RankingButtonDesc);\
REGISTER_DESCSTORE_EX(RankingDescEx);\
REGISTER_DESCSTORE(WaremblemWaremblemDesc);\
REGISTER_DESCSTORE(WaremblemLvDesc);\
REGISTER_DESCSTORE(WaremblemStarDesc);\
REGISTER_DESCSTORE_EX(WaremblemDescEx);\
REGISTER_DESCSTORE(Pk1v1RankDesc);\
REGISTER_DESCSTORE(Pk1v1RewardDesc);\
REGISTER_DESCSTORE(Pk1v1DailyrewardDesc);\
REGISTER_DESCSTORE_EX(Pk1v1DescEx);\
REGISTER_DESCSTORE(ConflateEquipDesc);\
REGISTER_DESCSTORE(ConflateGrouptypeDesc);\
REGISTER_DESCSTORE(ConflateSubtypeDesc);\
REGISTER_DESCSTORE(ConflatePropDesc);\
REGISTER_DESCSTORE(ConflateJewelry_spDesc);\
REGISTER_DESCSTORE(ConflateJewelry_zlDesc);\
REGISTER_DESCSTORE(ConflateJewelry_sjDesc);\
REGISTER_DESCSTORE_EX(ConflateDescEx);\
REGISTER_DESCSTORE(DragonsoulHoleDesc);\
REGISTER_DESCSTORE(DragonsoulOfferexpDesc);\
REGISTER_DESCSTORE(DragonsoulStrongexpDesc);\
REGISTER_DESCSTORE(DragonsoulFlyexpDesc);\
REGISTER_DESCSTORE(DragonsoulFlyattDesc);\
REGISTER_DESCSTORE(DragonsoulFlyDesc);\
REGISTER_DESCSTORE(DragonsoulAwakeDesc);\
REGISTER_DESCSTORE(DragonsoulNameDesc);\
REGISTER_DESCSTORE(DragonsoulStarcollectDesc);\
REGISTER_DESCSTORE_EX(DragonsoulDescEx);\
REGISTER_DESCSTORE(PersonalshopShopitemsDesc);\
REGISTER_DESCSTORE(PersonalshopShopsDesc);\
REGISTER_DESCSTORE_EX(PersonalshopDescEx);\
REGISTER_DESCSTORE(WashpartyWashpartyDesc);\
REGISTER_DESCSTORE(WashpartyExpDesc);\
REGISTER_DESCSTORE_EX(WashpartyDescEx);\
REGISTER_DESCSTORE(WelfareSignDesc);\
REGISTER_DESCSTORE(WelfareAccruerewardDesc);\
REGISTER_DESCSTORE(WelfareLvrewardDesc);\
REGISTER_DESCSTORE(WelfareOnlineDesc);\
REGISTER_DESCSTORE(WelfareFraudDesc);\
REGISTER_DESCSTORE(WelfareWeekendgiftDesc);\
REGISTER_DESCSTORE(WelfareConstantDesc);\
REGISTER_DESCSTORE(WelfareQifuDesc);\
REGISTER_DESCSTORE(WelfareWishDesc);\
REGISTER_DESCSTORE(WelfareLogonDesc);\
REGISTER_DESCSTORE(WelfareFirstchargeDesc);\
REGISTER_DESCSTORE(WelfareSctypeDesc);\
REGISTER_DESCSTORE(WelfareMibaoDesc);\
REGISTER_DESCSTORE(WelfareKfleichongDesc);\
REGISTER_DESCSTORE(WelfareDailygiftDesc);\
REGISTER_DESCSTORE(WelfareLcgiftDesc);\
REGISTER_DESCSTORE(WelfareLcraffleDesc);\
REGISTER_DESCSTORE(WelfareLcturntableDesc);\
REGISTER_DESCSTORE(WelfareJackpotDesc);\
REGISTER_DESCSTORE(WelfareMonthlycardDesc);\
REGISTER_DESCSTORE(WelfareGoalDesc);\
REGISTER_DESCSTORE(WelfareGoaltaskDesc);\
REGISTER_DESCSTORE(WelfareInvestDesc);\
REGISTER_DESCSTORE(WelfareInvestrewardDesc);\
REGISTER_DESCSTORE(WelfareYttlgiftDesc);\
REGISTER_DESCSTORE_EX(WelfareDescEx);\
REGISTER_DESCSTORE(QypeakBackDesc);\
REGISTER_DESCSTORE(QypeakConstantDesc);\
REGISTER_DESCSTORE_EX(QypeakDescEx);\
REGISTER_DESCSTORE(Pk3v3LevelDesc);\
REGISTER_DESCSTORE(Pk3v3RewardDesc);\
REGISTER_DESCSTORE(Pk3v3BadgeDesc);\
REGISTER_DESCSTORE(Pk3v3ConstantDesc);\
REGISTER_DESCSTORE(Pk3v3ExpDesc);\
REGISTER_DESCSTORE_EX(Pk3v3DescEx);\
REGISTER_DESCSTORE_EX(GuideDescEx);\
REGISTER_DESCSTORE(CloudpeakRankrewardsDesc);\
REGISTER_DESCSTORE(CloudpeakConstantDesc);\
REGISTER_DESCSTORE(CloudpeakExpDesc);\
REGISTER_DESCSTORE_EX(CloudpeakDescEx);\
REGISTER_DESCSTORE(XiuzhenroadTaskDesc);\
REGISTER_DESCSTORE(XiuzhenroadBonuspointsDesc);\
REGISTER_DESCSTORE(XiuzhenroadSkillDesc);\
REGISTER_DESCSTORE(XiuzhenroadClassifyDesc);\
REGISTER_DESCSTORE_EX(XiuzhenroadDescEx);\
REGISTER_DESCSTORE(GiftFreeDesc);\
REGISTER_DESCSTORE(GiftConditionDesc);\
REGISTER_DESCSTORE(GiftMustDesc);\
REGISTER_DESCSTORE_EX(GiftDescEx);\
REGISTER_DESCSTORE(BattlepassBattlepassDesc);\
REGISTER_DESCSTORE(BattlepassRewardDesc);\
REGISTER_DESCSTORE(BattlepassTaskDesc);\
REGISTER_DESCSTORE(BattlepassShopDesc);\
REGISTER_DESCSTORE_EX(BattlepassDescEx);\
REGISTER_DESCSTORE(FindtreasureFindtreasureDesc);\
REGISTER_DESCSTORE(FindtreasureFindpoolDesc);\
REGISTER_DESCSTORE(FindtreasureConstantDesc);\
REGISTER_DESCSTORE(FindtreasureTotalDesc);\
REGISTER_DESCSTORE(FindtreasureActiveDesc);\
REGISTER_DESCSTORE(FindtreasureActiveupDesc);\
REGISTER_DESCSTORE(FindtreasureActivegoodsDesc);\
REGISTER_DESCSTORE(FindtreasureActiveshopDesc);\
REGISTER_DESCSTORE(FindtreasureShopDesc);\
REGISTER_DESCSTORE_EX(FindtreasureDescEx);\
REGISTER_DESCSTORE(FestivalPeriodindexDesc);\
REGISTER_DESCSTORE(FestivalFestivalDesc);\
REGISTER_DESCSTORE(FestivalTemplateDesc);\
REGISTER_DESCSTORE(FestivalMuban_consumerankDesc);\
REGISTER_DESCSTORE(FestivalMuban_eggsdrawDesc);\
REGISTER_DESCSTORE(FestivalMuban_eggsdraw_poolDesc);\
REGISTER_DESCSTORE(FestivalMuban_eggsdraw_taskDesc);\
REGISTER_DESCSTORE(FestivalMuban_ftrewardDesc);\
REGISTER_DESCSTORE(FestivalMuban_challengeDesc);\
REGISTER_DESCSTORE(FestivalMuban_mystmallDesc);\
REGISTER_DESCSTORE(FestivalMuban_mystmall_mallDesc);\
REGISTER_DESCSTORE(FestivalMuban_rebatestoreDesc);\
REGISTER_DESCSTORE(FestivalMuban_rebatestore_mallDesc);\
REGISTER_DESCSTORE(FestivalMuban_contrechargeDesc);\
REGISTER_DESCSTORE(FestivalMuban_contrecharge_totalDesc);\
REGISTER_DESCSTORE(FestivalMuban_contrecharge_dayDesc);\
REGISTER_DESCSTORE(FestivalMuban_loginDesc);\
REGISTER_DESCSTORE(FestivalMuban_firstrechargeDesc);\
REGISTER_DESCSTORE(FestivalMuban_loveDesc);\
REGISTER_DESCSTORE(FestivalMuban_love_rankDesc);\
REGISTER_DESCSTORE(FestivalMuban_love_rank_dataDesc);\
REGISTER_DESCSTORE(FestivalMuban_love_taskDesc);\
REGISTER_DESCSTORE(FestivalMuban_love_taskrewardDesc);\
REGISTER_DESCSTORE(FestivalMuban_addboxDesc);\
REGISTER_DESCSTORE(FestivalMuban_doubleboxDesc);\
REGISTER_DESCSTORE(FestivalMuban_bossfristkillDesc);\
REGISTER_DESCSTORE(FestivalMuban_severrankDesc);\
REGISTER_DESCSTORE(FestivalMuban_severrank_dataDesc);\
REGISTER_DESCSTORE(FestivalMuban_collectwordDesc);\
REGISTER_DESCSTORE(FestivalMuban_signDesc);\
REGISTER_DESCSTORE(FestivalMuban_shopDesc);\
REGISTER_DESCSTORE(FestivalMuban_rechangeDesc);\
REGISTER_DESCSTORE(FestivalMuban_leijiDesc);\
REGISTER_DESCSTORE(FestivalZadanconstantDesc);\
REGISTER_DESCSTORE(FestivalMuban_zadanDesc);\
REGISTER_DESCSTORE(FestivalMuban_turntableDesc);\
REGISTER_DESCSTORE(FestivalMuban_turntable_poolDesc);\
REGISTER_DESCSTORE(FestivalMuban_turntable_taskDesc);\
REGISTER_DESCSTORE(FestivalMuban_donateDesc);\
REGISTER_DESCSTORE(FestivalMuban_donate_severDesc);\
REGISTER_DESCSTORE(FestivalMuban_donate_singleDesc);\
REGISTER_DESCSTORE(FestivalMuban_donate_taskDesc);\
REGISTER_DESCSTORE(FestivalMuban_onlineDesc);\
REGISTER_DESCSTORE(FestivalMuban_rturntableDesc);\
REGISTER_DESCSTORE(FestivalMuban_rturntable_rechargeDesc);\
REGISTER_DESCSTORE(FestivalMuban_rturntable_recharge_ratioDesc);\
REGISTER_DESCSTORE(FestivalMuban_drawpizeDesc);\
REGISTER_DESCSTORE(FestivalMuban_drawpize_poolDesc);\
REGISTER_DESCSTORE(FestivalMuban_drawpize_totalDesc);\
REGISTER_DESCSTORE(FestivalMuban_totalrechargeDesc);\
REGISTER_DESCSTORE(FestivalMuban_dailytotalrechargeDesc);\
REGISTER_DESCSTORE(FestivalMuban_rechargeprizeDesc);\
REGISTER_DESCSTORE(FestivalMuban_rptaskDesc);\
REGISTER_DESCSTORE(FestivalMuban_rppoolDesc);\
REGISTER_DESCSTORE(FestivalMuban_playDesc);\
REGISTER_DESCSTORE(FestivalMuban_play_rewardDesc);\
REGISTER_DESCSTORE(FestivalMuban_play_gameDesc);\
REGISTER_DESCSTORE(FestivalMuban_play_scoreDesc);\
REGISTER_DESCSTORE_EX(FestivalDescEx);\
REGISTER_DESCSTORE(MarketMarketDesc);\
REGISTER_DESCSTORE(MarketBigDesc);\
REGISTER_DESCSTORE(MarketSmallDesc);\
REGISTER_DESCSTORE(MarketConstantDesc);\
REGISTER_DESCSTORE_EX(MarketDescEx);\
REGISTER_DESCSTORE(DragonFragmentDesc);\
REGISTER_DESCSTORE(DragonDisplayDesc);\
REGISTER_DESCSTORE(DragonChangeDesc);\
REGISTER_DESCSTORE(DragonLvvalueDesc);\
REGISTER_DESCSTORE(DragonStarvalueDesc);\
REGISTER_DESCSTORE_EX(DragonDescEx);\
REGISTER_DESCSTORE(YanglongYanglongDesc);\
REGISTER_DESCSTORE(YanglongZadanDesc);\
REGISTER_DESCSTORE(YanglongRankingDesc);\
REGISTER_DESCSTORE_EX(YanglongDescEx);\
REGISTER_DESCSTORE_EX(TimelineDescEx);\
REGISTER_DESCSTORE(JinglianSimpleDesc);\
REGISTER_DESCSTORE(JinglianLvDesc);\
REGISTER_DESCSTORE(JinglianRaceDesc);\
REGISTER_DESCSTORE(JinglianCostDesc);\
REGISTER_DESCSTORE(JinglianGmDesc);\
REGISTER_DESCSTORE_EX(JinglianDescEx);\
REGISTER_DESCSTORE(EquipimproveUpqualityDesc);\
REGISTER_DESCSTORE(EquipimproveAwakenDesc);\
REGISTER_DESCSTORE(EquipimproveSoaringDesc);\
REGISTER_DESCSTORE(EquipimproveSealDesc);\
REGISTER_DESCSTORE(EquipimproveSealslotDesc);\
REGISTER_DESCSTORE(EquipimproveSealsuitDesc);\
REGISTER_DESCSTORE_EX(EquipimproveDescEx);\
REGISTER_DESCSTORE(TeleportTeleportDesc);\
REGISTER_DESCSTORE_EX(TeleportDescEx);\
REGISTER_DESCSTORE(XingchenXcsetupDesc);\
REGISTER_DESCSTORE(XingchenXcmosaicDesc);\
REGISTER_DESCSTORE(XingchenXcmaterialDesc);\
REGISTER_DESCSTORE(XingchenXinchenDesc);\
REGISTER_DESCSTORE(XingchenXclvattDesc);\
REGISTER_DESCSTORE(XingchenXclvexpDesc);\
REGISTER_DESCSTORE(XingchenXctpDesc);\
REGISTER_DESCSTORE(XingchenXctpexpDesc);\
REGISTER_DESCSTORE(XingchenXctpaddiDesc);\
REGISTER_DESCSTORE(XingchenXctpattDesc);\
REGISTER_DESCSTORE(XingchenXcstarDesc);\
REGISTER_DESCSTORE(XingchenXcawakenDesc);\
REGISTER_DESCSTORE(XingchenXcmagicalDesc);\
REGISTER_DESCSTORE(XingchenXcmagattDesc);\
REGISTER_DESCSTORE(XingchenXcadvattDesc);\
REGISTER_DESCSTORE(XingchenXcguizhenDesc);\
REGISTER_DESCSTORE(XingchenXingjunDesc);\
REGISTER_DESCSTORE(XingchenXjattDesc);\
REGISTER_DESCSTORE(XingchenXingjiDesc);\
REGISTER_DESCSTORE(XingchenXjcwDesc);\
REGISTER_DESCSTORE(XingchenXjlvexpDesc);\
REGISTER_DESCSTORE(XingchenZbshopDesc);\
REGISTER_DESCSTORE_EX(XingchenDescEx);\
REGISTER_DESCSTORE(MofaSetupDesc);\
REGISTER_DESCSTORE(MofaYuansuDesc);\
REGISTER_DESCSTORE(MofaDecomposeDesc);\
REGISTER_DESCSTORE(MofaLvexpDesc);\
REGISTER_DESCSTORE(MofaLvattDesc);\
REGISTER_DESCSTORE(MofaZyattDesc);\
REGISTER_DESCSTORE(MofaZyjxattDesc);\
REGISTER_DESCSTORE(MofaZyjxzfattDesc);\
REGISTER_DESCSTORE(MofaExchangeDesc);\
REGISTER_DESCSTORE(MofaNameDesc);\
REGISTER_DESCSTORE_EX(MofaDescEx);\
REGISTER_DESCSTORE(ShentiConstantDesc);\
REGISTER_DESCSTORE(ShentiPreposeDesc);\
REGISTER_DESCSTORE(ShentiUpgradeDesc);\
REGISTER_DESCSTORE(ShentiRemanieDesc);\
REGISTER_DESCSTORE(ShentiEquipDesc);\
REGISTER_DESCSTORE(ShentiAttributeDesc);\
REGISTER_DESCSTORE(ShentiStrongDesc);\
REGISTER_DESCSTORE(ShentiEvolveDesc);\
REGISTER_DESCSTORE(ShentiEvolveprogressDesc);\
REGISTER_DESCSTORE(ShentiStarlibraryDesc);\
REGISTER_DESCSTORE(ShentiAwakenDesc);\
REGISTER_DESCSTORE(ShentiAwakenprogressDesc);\
REGISTER_DESCSTORE(ShentiSuitDesc);\
REGISTER_DESCSTORE(ShentiComposeDesc);\
REGISTER_DESCSTORE(ShentiStar_upDesc);\
REGISTER_DESCSTORE(ShentiStrengtitelDesc);\
REGISTER_DESCSTORE(ShentiStartitelDesc);\
REGISTER_DESCSTORE_EX(ShentiDescEx);\
REGISTER_DESCSTORE(XiuzhenworldWorldDesc);\
REGISTER_DESCSTORE(XiuzhenworldConstantDesc);\
REGISTER_DESCSTORE(XiuzhenworldExpmapDesc);\
REGISTER_DESCSTORE_EX(XiuzhenworldDescEx);\
REGISTER_DESCSTORE(SoulOpenDesc);\
REGISTER_DESCSTORE(SoulSoulDesc);\
REGISTER_DESCSTORE(Soul3dmodelDesc);\
REGISTER_DESCSTORE(SoulSoulbasicDesc);\
REGISTER_DESCSTORE(SoulSouladvanceDesc);\
REGISTER_DESCSTORE(SoulBlessDesc);\
REGISTER_DESCSTORE(SoulPrivilegeDesc);\
REGISTER_DESCSTORE(SoulCrystalDesc);\
REGISTER_DESCSTORE(SoulCrystallvDesc);\
REGISTER_DESCSTORE(SoulCrystaltopDesc);\
REGISTER_DESCSTORE(SoulCrystalholeDesc);\
REGISTER_DESCSTORE(SoulFusionDesc);\
REGISTER_DESCSTORE(SoulAttrDesc);\
REGISTER_DESCSTORE(SoulSkillDesc);\
REGISTER_DESCSTORE(SoulBoneDesc);\
REGISTER_DESCSTORE(SoulBonekillDesc);\
REGISTER_DESCSTORE(SoulBonestrongDesc);\
REGISTER_DESCSTORE(SoulGuwenDesc);\
REGISTER_DESCSTORE(SoulGuwentypeDesc);\
REGISTER_DESCSTORE(SoulGuwentypesuitDesc);\
REGISTER_DESCSTORE(SoulGuwenskillDesc);\
REGISTER_DESCSTORE(SoulGuwensuitDesc);\
REGISTER_DESCSTORE(SoulAffixesDesc);\
REGISTER_DESCSTORE(SoulAffixesfumoDesc);\
REGISTER_DESCSTORE(SoulAffixessuitDesc);\
REGISTER_DESCSTORE(SoulGuwenattrDesc);\
REGISTER_DESCSTORE_EX(SoulDescEx);\
REGISTER_DESCSTORE(RuneConstDesc);\
REGISTER_DESCSTORE(RuneRuneDesc);\
REGISTER_DESCSTORE(RuneRunewordsDesc);\
REGISTER_DESCSTORE(RuneQuenchingDesc);\
REGISTER_DESCSTORE(RuneCompareDesc);\
REGISTER_DESCSTORE(RuneStuntskillDesc);\
REGISTER_DESCSTORE(RunePassiveskillDesc);\
REGISTER_DESCSTORE(RuneUpgradeDesc);\
REGISTER_DESCSTORE(RuneUpgradeexpDesc);\
REGISTER_DESCSTORE(RuneAdvancedDesc);\
REGISTER_DESCSTORE(RuneSoaringDesc);\
REGISTER_DESCSTORE(RuneHandbookDesc);\
REGISTER_DESCSTORE_EX(RuneDescEx);\
REGISTER_DESCSTORE(NickgodConstantDesc);\
REGISTER_DESCSTORE(NickgodNameDesc);\
REGISTER_DESCSTORE(NickgodStageDesc);\
REGISTER_DESCSTORE(NickgodRewardsDesc);\
REGISTER_DESCSTORE(NickgodLatticeDesc);\
REGISTER_DESCSTORE(NickgodTreasuryDesc);\
REGISTER_DESCSTORE(NickgodPrivilegeDesc);\
REGISTER_DESCSTORE(NickgodSaleDesc);\
REGISTER_DESCSTORE(NickgodChargeupDesc);\
REGISTER_DESCSTORE_EX(NickgodDescEx);\
REGISTER_DESCSTORE(TianxiafirstConstantDesc);\
REGISTER_DESCSTORE(TianxiafirstBattleDesc);\
REGISTER_DESCSTORE(TianxiafirstArtifactDesc);\
REGISTER_DESCSTORE(TianxiafirstStrongDesc);\
REGISTER_DESCSTORE(TianxiafirstStrongitemDesc);\
REGISTER_DESCSTORE(TianxiafirstRefineDesc);\
REGISTER_DESCSTORE(TianxiafirstSqskillDesc);\
REGISTER_DESCSTORE(TianxiafirstGradeDesc);\
REGISTER_DESCSTORE(TianxiafirstGraderewardDesc);\
REGISTER_DESCSTORE(TianxiafirstRankrewardDesc);\
REGISTER_DESCSTORE(TianxiafirstWatchrewardDesc);\
REGISTER_DESCSTORE(TianxiafirstLuckyrewardDesc);\
REGISTER_DESCSTORE(TianxiafirstMatchtimesrewardDesc);\
REGISTER_DESCSTORE(TianxiafirstMatchresultrewardDesc);\
REGISTER_DESCSTORE(TianxiafirstExtraaddattrDesc);\
REGISTER_DESCSTORE(TianxiafirstFirstaddattrDesc);\
REGISTER_DESCSTORE(TianxiafirstShopDesc);\
REGISTER_DESCSTORE(TianxiafirstDanmakuDesc);\
REGISTER_DESCSTORE_EX(TianxiafirstDescEx);\
REGISTER_DESCSTORE(WordshoutShoutDesc);\
REGISTER_DESCSTORE_EX(WordshoutDescEx);\
REGISTER_DESCSTORE_EX(LoginDescEx);\
REGISTER_DESCSTORE(CloakActivateDesc);\
REGISTER_DESCSTORE(CloakValueDesc);\
REGISTER_DESCSTORE(CloakIntensifyitemDesc);\
REGISTER_DESCSTORE(CloakRefineDesc);\
REGISTER_DESCSTORE(CloakRefineunlockDesc);\
REGISTER_DESCSTORE(CloakGradeDesc);\
REGISTER_DESCSTORE(CloakGodDesc);\
REGISTER_DESCSTORE(CloakSoulDesc);\
REGISTER_DESCSTORE(CloakSoulactiveDesc);\
REGISTER_DESCSTORE(CloakSoullvDesc);\
REGISTER_DESCSTORE(CloakSoulclearDesc);\
REGISTER_DESCSTORE(CloakSoulachievementDesc);\
REGISTER_DESCSTORE_EX(CloakDescEx);\
REGISTER_DESCSTORE(QunxiongzhuluConstantDesc);\
REGISTER_DESCSTORE(QunxiongzhuluSkillDesc);\
REGISTER_DESCSTORE(QunxiongzhuluServerrankDesc);\
REGISTER_DESCSTORE(QunxiongzhuluWorldrankDesc);\
REGISTER_DESCSTORE(QunxiongzhuluLocalrankDesc);\
REGISTER_DESCSTORE(QunxiongzhuluBossrewardDesc);\
REGISTER_DESCSTORE_EX(QunxiongzhuluDescEx);\
REGISTER_DESCSTORE(PeakbattleConstantDesc);\
REGISTER_DESCSTORE(PeakbattleAwardDesc);\
REGISTER_DESCSTORE(PeakbattleGuessDesc);\
REGISTER_DESCSTORE_EX(PeakbattleDescEx);\

