// -------------------------------------------------------------------------
//    @FileName         :    NFTypeDefines.h
//    @Author           :    Gao.Yi
//    @Date             :   2022-09-18
//    @Email			:    445267987@qq.com
//    @Module           :    NFPluginModule
//
// -------------------------------------------------------------------------

#pragma once
#include "NFComm/NFCore/NFPlatform.h"
#include "NFComm/NFShmCore/NFTypeDefines.h"

typedef enum
{
    EOT_DS_BEGIN_ID = EOT_DESC_STORE_BEGIN_ID,
    EOT_CONST_MSG_PHPMSG_DESC_ID,
    EOT_CONST_UI_EFFECT_DESC_ID,
    EOT_CONST_ROLE_BORN_DESC_ID,
    EOT_CONST_ROLE_WARRIOR_DESC_ID,
    EOT_CONST_ROLE_MASTER_DESC_ID,
    EOT_CONST_ROLE_ASSASSIN_DESC_ID,
    EOT_CONST_ROLE_SHOOTER_DESC_ID,
    EOT_CONST_ROLE_EXP_DESC_ID,
    EOT_CONST_ROLE_SKILLTYPE_DESC_ID,
    EOT_CONST_ROLE_ADDSKILL_DESC_ID,
    EOT_CONST_ROLE_WORLDEXP_DESC_ID,
    EOT_CONST_RANDOMNAME_MANFIRST_DESC_ID,
    EOT_CONST_RANDOMNAME_MANSECOND_DESC_ID,
    EOT_CONST_RANDOMNAME_MANTHIRD_DESC_ID,
    EOT_CONST_RANDOMNAME_WOMANFIRST_DESC_ID,
    EOT_CONST_RANDOMNAME_WOMANSECOND_DESC_ID,
    EOT_CONST_RANDOMNAME_WOMANTHIRD_DESC_ID,
    EOT_CONST_SENSITIVEWORD_SENSITIVE_WORD_DESC_ID,
    EOT_CONST_SENSITIVEWORD_ROLESENSITIVE_DESC_ID,
    EOT_CONST_MAP_MAP_DESC_ID,
    EOT_CONST_MAP_ITEMDROP_DESC_ID,
    EOT_CONST_MAP_DESTROYITEM_DESC_ID,
    EOT_CONST_MONSTER_MONSTER_DESC_ID,
    EOT_CONST_MONSTER_DISPLAY_DESC_ID,
    EOT_CONST_MONSTER_VALUE_DESC_ID,
    EOT_CONST_AREA_AREA_DESC_ID,
    EOT_CONST_AREA_PATH_DESC_ID,
    EOT_CONST_SKILL_SKILL_DESC_ID,
    EOT_CONST_SKILL_BUFF_DESC_ID,
    EOT_CONST_ITEM_ITEM_DESC_ID,
    EOT_CONST_EQUIP_EQUIP_DESC_ID,
    EOT_CONST_CONSTANT_CONSTANT_DESC_ID,

    EOT_DS_END_ID = EOT_DESC_STORE_END_ID,
} EN_DESC_STORE_SHMOBJ_TYPE;