include ./define.makefile

.PHONY:all

all:${RESDB_BIN_FILE}

${EXCEL_MMO_PROTO_BIN_FILES} ${EXCEL_MMO_MAKEFILE_BIN_FILES}:${EXCEL_MMO_FILES}
	echo {EXCEL_MMO_PROTO_BIN_FILES}
	echo ${EXCEL_MMO_MAKEFILE_BIN_FILES}
	mkdir -p ${PROTOCGEN_FILE_PATH}
	for xml in $(EXCEL_MMO_FILES);do\
		${EXCEL2PROTO} --excel=$$xml --out_path=${PROTOCGEN_FILE_PATH}/;\
	done
	cp ${EXCEL_MMO_PROTO_BIN_FILES} ${EXCEL_MMO_MAKEFILE_BIN_FILES} ${RESDB_META_PATH} -rf
