include ./define.makefile

.PHONY:all

all:${RESDB_BIN_FILE}

${EXCEL_MMO_PROTO_BIN_FILES} ${EXCEL_MMO_MAKEFILE_BIN_FILES}:${EXCEL_MMO_FILES}
	mkdir -p ${PROTOCGEN_FILE_PATH}
	for xml in $(EXCEL_MMO_FILES);do\
		${EXCEL2PROTO} --excel=$$xml --out_path=${PROTOCGEN_FILE_PATH}/;\
	done
	${FILE_COPY_EXE} --src="${EXCEL_MMO_PROTO_BIN_FILES} ${EXCEL_MMO_MAKEFILE_BIN_FILES}" --dst=${RESDB_META_PATH}/
